### ISSUE TITLE
Add new release repositories: rosidl_core-release

### ISSUE THREAD

**Issue by jacobperron** [ros2-gbp/ros2-gbp-github-org#101]
* Name of the release team: ros2-team

* Release repositories to add:
  * [rosidl_core](https://github.com/ros2/rosidl_core)

**Comment by jacobperron** [comment]
FYI, @nuclearsandwich

**Comment by nuclearsandwich** [comment]
Done in https://github.com/ros2-gbp/ros2-gbp-github-org/pull/105
