### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by bjsowa** [ros2-gbp/ros2-gbp-github-org#104]
* Name of the new release team: fictionlab
* Release repositories to add:
  * [leo_common](https://github.com/LeoRover/leo_common-ros2)
    * [x] There is an existing release repository which should be imported: https://github.com/fictionlab-gbp/leo_common-ros2-release
  * [leo_robot](https://github.com/LeoRover/leo_robot-ros2)
    * [x] There is an existing release repository which should be imported: https://github.com/fictionlab-gbp/leo_robot-ros2-release
  * [leo_desktop](https://github.com/LeoRover/leo_desktop-ros2)
    * [x] There is an existing release repository which should be imported: https://github.com/fictionlab-gbp/leo_desktop-ros2-release

* Team members
  * @bjsowa
  * @szlachcic
  * @Bitterisland6

**Comment by bjsowa** [comment]
The `ros2` keyword in the imported release repositories should be omitted.

**Comment by nuclearsandwich** [comment]
The above release repositories have been imported. This change has been deployed!
