### ISSUE TITLE
Add new release repositories

### ISSUE THREAD

**Issue by christianrauch** [ros2-gbp/ros2-gbp-github-org#109]
* Name of the release team: apriltag

* Release repositories to add:
  * [apriltag_msgs](https://github.com/christianrauch/apriltag_msgs.git)
  * [apriltag_ros](https://github.com/christianrauch/apriltag_ros.git)

**Comment by nuclearsandwich** [comment]
Closing as a sibling of https://github.com/ros2-gbp/ros2-gbp-github-org/issues/108 to be re-opened once the associated discussions are settled.

**Comment by christianrauch** [comment]
The issue has been settled: https://github.com/AprilRobotics/apriltag_ros/issues/76#issuecomment-1324875645. Please reopen and consider adding the release repos for ROS2.

**Comment by nuclearsandwich** [comment]
This change has been deployed.
