### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by mbusy** [ros2-gbp/ros2-gbp-github-org#122]
* Name of the new release team: ros_naoqi
* Release repositories to add:
  * [libqi](https://github.com/ros-naoqi/libqi)
    * [x] There is an existing release repository which should be imported: https://github.com/ros-naoqi/libqi-release
  * [libqicore](https://github.com/ros-naoqi/libqicore)
    * [x] There is an existing release repository which should be imported: https://github.com/ros-naoqi/libqicore-release
  * [naoqi_bridge_msgs](https://github.com/ros-naoqi/naoqi_bridge_msgs)
    * [x] There is an existing release repository which should be imported: https://github.com/ros-naoqi/naoqi_bridge_msgs-release
  * [naoqi_driver](https://github.com/ros-naoqi/naoqi_driver)
    * [x] There is an existing release repository which should be imported: https://github.com/ros-naoqi/naoqi_driver-release
  * [nao_meshes](https://github.com/ros-naoqi/nao_meshes)
    * [x] There is an existing release repository which should be imported: https://github.com/ros-naoqi/nao_meshes-release
  * [pepper_meshes](https://github.com/ros-naoqi/pepper_meshes)
    * [x] There is an existing release repository which should be imported: https://github.com/ros-naoqi/pepper_meshes-release

* Team members
  * [@mbusy](https://github.com/ros-naoqi/libqi/blob/f7e2993c5ad78d31256cfa6472ebfd4950a5ffe5/package.xml#L7)
  * [@suryaambrose](https://github.com/ros-naoqi/libqi/blob/f7e2993c5ad78d31256cfa6472ebfd4950a5ffe5/package.xml#L8)
  * [@Karsten1987](https://github.com/ros-naoqi/naoqi_bridge_msgs/blob/8a90e60d9e159b273165de4f9b32cb2a4f9bd79c/package.xml#L7)
  * [@zygopter](https://github.com/ros-naoqi/naoqi_driver/blob/f25af125813c7d5992eca98f19fc7fa4f6bad916/package.xml#L8)
  * [@mikaelarguedas](https://github.com/ros-naoqi/pepper_meshes/blob/c750c7317ea865ac0314e80d4393767f2eac1c62/package.xml#L6)
  * [@nlyubova](https://github.com/ros-naoqi/pepper_meshes/blob/c750c7317ea865ac0314e80d4393767f2eac1c62/package.xml#L10)

**Comment by nuclearsandwich** [comment]
Apologies for the delay, this change has been deployed.
