### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by MADdantas** [ros2-gbp/ros2-gbp-github-org#130]
* Name of the new release team: mad
* Release repositories to add:
  * [create_robot](https://github.com/MADdantas/create_robot)
    * [x] There is an existing release repository which should be imported: https://github.com/MADdantas/create_robot_ros2-release
  * [libcreate](https://github.com/MADdantas/libcreate)
    * [x] There is an existing release repository which should be imported: https://github.com/MADdantas/libcreate_ros2-release

* Team members
  * @MADdantas

**Comment by jacobperron** [comment]
There already exists a release repository for `libcreate` here: https://github.com/AutonomyLab/libcreate-release

And `create_robot` (previously named `create_autonomy`) here: https://github.com/AutonomyLab/create_autonomy-release

**Comment by nuclearsandwich** [comment]
@jacobperron are you good with giving this collaborator permission to make ROS 2 releases?

Based on https://github.com/ros/rosdistro/pull/34724#issuecomment-1266133248 I wasn't quite sure.
is "mad" the correct release team name for these releases and should you be on it as well?

**Comment by MADdantas** [comment]
Don't need to give me permission. @jacobperron already made the releases. I've forget to close this issue
