### ISSUE TITLE
Add release team: dynamixel_community

### ISSUE THREAD

**Issue by youtalk** [ros2-gbp/ros2-gbp-github-org#139]
* Name of the new release team: dynamixel_community
* Release repositories to add:
  * [dynamixel_hardware](https://github.com/dynamixel-community/dynamixel_hardware)

* Team members
  * [@youtalk](https://github.com/youtalk)
  * [@ijnek](https://github.com/ijnek)
  * [@ROBOTIS-Will](https://github.com/ROBOTIS-Will)

**Comment by nuclearsandwich** [comment]
Hi @youtalk, I think we can put this issue on hold until https://github.com/ros/rosdistro/pull/34986#pullrequestreview-1147502846 is resolved.

I am going to close it for now but it can be re-opened it once those comments are addressed.

**Comment by youtalk** [comment]
Hi @nuclearsandwich, https://github.com/ros/rosdistro/pull/34986#pullrequestreview-1147502846 was resolved. Please consider to re-open this issue and review.
I've updated the description above.
