### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by huchijwk** [ros2-gbp/ros2-gbp-github-org#141]
* Name of the new release team:  42dot
* Release repositories to add:
  * [foros](https://github.com/42dot/foros)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

* Team members
  * [@huchijwk](https://github.com/42dot/foros/blob/c6bf98662bc7b27207f813b7111f2469e91a3425/foros/package.xml#L7)

**Comment by nuclearsandwich** [comment]
[Source entry in ros/rosdistro](https://github.com/ros/rosdistro/blob/91a4ac49a7093813a6183f5cb99280a52a85fc6c/humble/distribution.yaml#L1195-L1199) ✔️

**Comment by nuclearsandwich** [comment]
This change has been deployed.
