### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by christianrauch** [ros2-gbp/ros2-gbp-github-org#142]
* Name of the new release team: `libcamera`
* Release repositories to add:
  * [libcamera](https://git.libcamera.org/libcamera/libcamera.git)
  * [camera_ros](https://github.com/christianrauch/camera_ros.git)

* Team members
  * @christianrauch

**Comment by nuclearsandwich** [comment]
Holding off on this pending the discussion in https://github.com/ros/rosdistro/pull/35029

If it's possible to release camera_ros on top of the libcamera version in Ubuntu Jammy I can set up that release repo even though it won't be releasable until the rosdep keys are updated.

**Comment by christianrauch** [comment]
> If it's possible to release camera_ros on top of the libcamera version in Ubuntu Jammy

This is not possible since the system version uses an outdated API. Even if I would support both APIs via manual ifdefs, I see no value in releasing a ROS package that relies on an outdated camera driver library with limited functionality and support for cameras.

**Comment by nuclearsandwich** [comment]
> This is not possible since the system version uses an outdated API. Even if I would support both APIs via manual ifdefs, I see no value in releasing a ROS package that relies on an outdated camera driver library with limited functionality and support for cameras.

Thanks for the info, sounds good. Not knowing the exact situation myself I was trying to identify possible ways to make progress without blocking on the larger issue. With the info you've given I'm going to close this issue while we resolve things in the other discussion.

**Comment by christianrauch** [comment]
In the original discussion, we concluded (https://github.com/ros/rosdistro/pull/35029#issuecomment-1424914549) that the system libcamera package is broken and will not be fixed for Ubuntu 22.04, and thus that we can provide a `libcamera` bloomed package for Ubuntu 22.04 and use rosdep keys for distributions that have a working version of libcamera.

@nuclearsandwich Would you now consider adding the initially requested release repos?

**Comment by nuclearsandwich** [comment]
This change has been deployed!
