### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by ChloeWu1** [ros2-gbp/ros2-gbp-github-org#144]
# Updates to  membership.

## New team members

Link: https://github.com/intel/ros2_object_msgs/blob/master/package.xml
Users: https://github.com/lewisliupub & https://github.com/ChloeWu1

**Comment by nuclearsandwich** [comment]
@ChloeWu1 which team are you asking about?

**Comment by ChloeWu1** [comment]
> @ChloeWu1 which team are you asking about?

Hi, our team would like to release the "ros-dashing-object-msgs" package for other ROS2 versions, but we hard to find our origin team name. Could you please give us some suggestions for how we can sub-release it under this situation? Thanks for your help.

**Comment by nuclearsandwich** [comment]
I see. Thanks for the explanation.

The release team for that project, [object_analytics](https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/object_analytics.tf) is currently empty and once we verify that these are current maintainers of the project we can update the team to add you and your collaborators.

Looking at the source repositories for object_msgs and object_analytics I don't recognize either of the mentioned GitHub usernames as belonging to the listed maintainers. Could you please update the links in your request to highlight specific lines of the current package.xml for example

https://github.com/intel/ros2_object_msgs/blob/7abc200d6e0c14481cfd654794c0153d2bfd5ad6/package.xml#L25 which appears to be associated with the https://github.com/chaoli2 user on GitHub.

**Comment by ChloeWu1** [comment]
Thanks for your kindly help. Our team have updated the link of the package and users we would like to add. 
Package link: https://github.com/intel/ros2_object_msgs/blob/master/package.xml
New members: https://github.com/lewisliupub & https://github.com/ChloeWu1

**Comment by ChloeWu1** [comment]
> I see. Thanks for the explanation.
> 
> The release team for that project, [object_analytics](https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/object_analytics.tf) is currently empty and once we verify that these are current maintainers of the project we can update the team to add you and your collaborators.
> 
> Looking at the source repositories for object_msgs and object_analytics I don't recognize either of the mentioned GitHub usernames as belonging to the listed maintainers. Could you please update the links in your request to highlight specific lines of the current package.xml for example
> 
> https://github.com/intel/ros2_object_msgs/blob/7abc200d6e0c14481cfd654794c0153d2bfd5ad6/package.xml#L25 which appears to be associated with the https://github.com/chaoli2 user on GitHub.

Hi. Thanks for your suggestion.

Our team has updated the package and new member lists recently. However, we would like to know if we need to ask origin authors such as chaoli2 for authorization or verification?

**Comment by nuclearsandwich** [comment]
> Our team has updated the package and new member lists recently. However, we would like to know if we need to ask origin authors such as chaoli2 for authorization or verification?

If you can update the package sources then confirmation from previous maintainers is not required. If the original sources cannot be updated but you have a fork that is being maintained there is a separate, more involved process for taking over from absentee maintainers.

Since I cannot see the member lists for repositories the best thing to do is update the maintainers listed in each repository's package.xml file.

**Comment by ChloeWu1** [comment]
Hi, we have updated the member lists for repositories. 
Link: https://github.com/intel/ros2_object_msgs/blob/master/package.xml.
New members added: https://github.com/lewisliupub & https://github.com/ChloeWu1
Could you please give us some suggestions about next steps for sub-release? Thanks for your help.

**Comment by ChloeWu1** [comment]
> I see. Thanks for the explanation.
> 
> The release team for that project, [object_analytics](https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/object_analytics.tf) is currently empty and once we verify that these are current maintainers of the project we can update the team to add you and your collaborators.
> 
> Looking at the source repositories for object_msgs and object_analytics I don't recognize either of the mentioned GitHub usernames as belonging to the listed maintainers. Could you please update the links in your request to highlight specific lines of the current package.xml for example
> 
> https://github.com/intel/ros2_object_msgs/blob/7abc200d6e0c14481cfd654794c0153d2bfd5ad6/package.xml#L25 which appears to be associated with the https://github.com/chaoli2 user on GitHub.

Hi, Thanks for your suggestion. Our team has updated the maintainer in Link: https://github.com/intel/ros2_object_msgs/blob/master/package.xml.
New members:
maintainer email="wei.zhi.liu@intel.com">Weizhi Liu
maintainer email="jiawei.wu@intel.com">Jiawei Wu
Could you please verify it and add me and my collaborators to the [object_analytics](https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/object_analytics.tf)? So that we could sub-release the ros2_object_msgs to other ROS versions. Thanks!
