### ISSUE TITLE
Add new release repositories

### ISSUE THREAD

**Issue by huchijwk** [ros2-gbp/ros2-gbp-github-org#152]
* Name of the release team: 42dot

* Release repositories to add:
  * [foros](https://github.com/42dot/foros)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

**Comment by nuclearsandwich** [comment]
@huchijwk this release repository was added when I created the new team for https://github.com/ros2-gbp/ros2-gbp-github-org/issues/141

Is there an additional release repository for another project or can this issue be closed?

**Comment by huchijwk** [comment]
@nuclearsandwich Thanks for your reply. I checked that `42dot-release` was created, is it correct that the release repository is created with the team name not repository name, `foros-release`?

**Comment by nuclearsandwich** [comment]
🤦🏼 That was me typing faster than I was thinking. I'll open a PR to change the repo name and rename it. Sorry for the trouble.

**Comment by nuclearsandwich** [comment]
The latest change renaming the release repository is deploying now.

**Comment by huchijwk** [comment]
Thanks!
