### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by Myzhar** [ros2-gbp/ros2-gbp-github-org#159]
* Name of the new release team: myzhar
* Release repositories to add:
  * [ldrobot-lidar-ros2](https://github.com/Myzhar/ldrobot-lidar-ros2)
    * [ ] There is an existing release repository which should be imported: https://github.com/Myzhar/ldrobot-lidar-ros2/releases

* Team members
  * [@myzhar](https://github.com/Myzhar/ldrobot-lidar-ros2/blob/main/ldlidar_node/package.xml)

**Comment by nuclearsandwich** [comment]
Hi @Myzhar, before we can set up this release repository, the package should undergo the initial [REP-144] naming review. Can you please open a PR on https://github.com/ros/rosdistro adding a source entry for this package in `humble/distribution.yaml` that will trigger our naming review process and once the source entry is present we can continue setting up the release repository.

**Comment by Myzhar** [comment]
Done:
https://github.com/ros/rosdistro/pull/35600

**Comment by nuclearsandwich** [comment]
Closing while https://github.com/ros/rosdistro/pull/35600 is still pending. @Myzhar please re-open this once your repository has been added to the rosdistro index after following the suggestions in https://github.com/ros/rosdistro/pull/35600#issuecomment-1382585462
