### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by miferco97** [ros2-gbp/ros2-gbp-github-org#166]
* Name of the new release team: aerostack2
* Release repositories to add:
  * [aerostack2](https://github.com/aerostack2/aerostack2)
    * [ ] There is an existing release repository which should be imported: <https://github.com/aerostack2/aerostack2-release.git>

* Team members  (https://github.com/aerostack2/aerostack2/blob/main/aerostack2/package.xml)
  * @miferco97
  * @pariaspe
  * @RPS98
  * @perezsaura-david

**Comment by tfoote** [comment]
Thanks for opening this request. Most of the team is on holiday break, but we plan to review PRs to this repository early in the new year.

**Comment by nuclearsandwich** [comment]
Hi @miferco97, thanks again for your patience as we ramp back into release repo admin after the end of year holidays.

Before release repositories are created, repositories and packages should be submitted to the official rosdistro repository https://github.com/ros/rosdistro for naming review.
Guidelines for package naming are describe in REP-144: https://www.ros.org/reps/rep-0144.html

This section of the current contribution guideline is the best guide for the process so far https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#documentation-indexing some of the information may only apply to ROS 1 packages but opening a PR for source and doc entries for any ROS 2 distribution will be enough to trigger the naming review.

I have opened #173 which implements this request but I have left it in draft pending the naming review above.

**Comment by miferco97** [comment]
Thanks @nuclearsandwich we have made some name changes at https://github.com/aerostack2/aerostack2 to fulfill REP-144, do we have to create the issue again?

**Comment by nuclearsandwich** [comment]
> do we have to create the issue again?

No that's not necessary, but if you could please open the documentation indexing request PR described above and then link that here, we can move forward with the release repository setup once indexing is complete.

**Comment by nuclearsandwich** [comment]
This change has been deployed!
