### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by stefanscherzinger** [ros2-gbp/ros2-gbp-github-org#169]
* Name of the new release team: schunk_svh
* Release repositories to add:
  * [schunk_svh_library](https://github.com/fzi-forschungszentrum-informatik/schunk_svh_library.git)
  * [schunk_svh_ros_driver](https://github.com/fzi-forschungszentrum-informatik/schunk_svh_ros_driver.git)

* Team members
  * [@stefanscherzinger](https://github.com/fzi-forschungszentrum-informatik/schunk_svh_ros_driver/blob/ros2-humble/schunk_svh_driver/package.xml#L9)
  * ...

**Comment by nuclearsandwich** [comment]
This change has been deployed!
