### ISSUE TITLE
Add release team locusrobotics

### ISSUE THREAD

**Issue by sloretz** [ros2-gbp/ros2-gbp-github-org#171]
* Name of the new release team: `locusrobotics`
* Release repositories to add:
  * [fuse](https://github.com/locusrobotics/fuse)
  * [tf2_2d](https://github.com/locusrobotics/tf2_2d/)

* Team members
  * @svwilliams [package author](https://github.com/locusrobotics/fuse/blob/3860ca3de512b318bc49c4eb9b941552630758a6/fuse/package.xml#L10)

**Comment by nuclearsandwich** [comment]
This change has been deployed!
