### ISSUE TITLE
Add new release repository: joy_tester

### ISSUE THREAD

**Issue by joshnewans** [ros2-gbp/ros2-gbp-github-org#179]
* Name of the release team: 
`josh_newans`

* Release repositories to add:
  * [joy_tester](https://github.com/joshnewans/joy_tester)

Note the initial rosdistro PRs are still pending

**Comment by nuclearsandwich** [comment]
Before release repositories are created, repositories and packages should be submitted to the official rosdistro repository https://github.com/ros/rosdistro for naming review.
Guidelines for package naming are describe in REP-144: https://www.ros.org/reps/rep-0144.html

This section of the current contribution guideline is the best guide for the process so far https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#documentation-indexing some of the information may only apply to ROS 1 packages but opening a PR for source and doc entries for any ROS 2 distribution will be enough to trigger the naming review.

Please open the ros/rosdistro PR and link it in this issue. Once your package has been reviewed and index we can proceed with the release repository configuration.

**Comment by joshnewans** [comment]
Thanks! Sorry about that, and no worries, Rosdistro PRs are linked below:

- https://github.com/ros/rosdistro/pull/35881
- https://github.com/ros/rosdistro/pull/35882
- https://github.com/ros/rosdistro/pull/35883

**Comment by nuclearsandwich** [comment]
Thanks @joshnewans, for future reference it's only strictly required to get your package indexed in one active distribution. That's enough to get the naming review and then when you first release your package into the other distributions there will be a prompt to add source and doc indexing along with the release. But there is also nothing wrong with having it indexed everywhere first as that will give the devel jobs time to run before your first releases are packaged.

**Comment by joshnewans** [comment]
Thanks @nuclearsandwich! So this one can be processed now yeah? (Even though humble is being held for sync) Or would you prefer to wait for the humble sync to be done? I don't mind, as long as that doesn't then mean I miss the next foxy/rolling sync for the binary release.

Re the process, as I did it I thought: "putting them both up now will be more efficient, once the rosdistro PRs are approved this one can be approved without the delay of it going back and forth between them and me". But straight after that it occurred to me that it's probably more efficient the other way, as I'm the one who is actually paying attention to where my package is at, rather than creating more busywork for you guys (seeing one here you can't push through, and having to actively check the rosdistro PRs, or if you are the person approving the rosdistro one, to then remember to come back here). And even though the back-and-forth is a bit annoying, it means that any time you see an issue/PR it should be good to go.

So sorry for that little hurdle - I'll do it right next time ;)

**Comment by nuclearsandwich** [comment]
> ! So this one can be processed now yeah?

Yep, there was no additional blocker here. I was processing those on rosdistro duty and didn't want to break stride to switch to ros2-gbp admin. I try to make at least one full pass here per week but this week has been super busy so I'm late getting to it.

> So sorry for that little hurdle - I'll do it right next time ;)

No worries. There wasn't any additional overhead for us.

#179 adds this repository.

**Comment by nuclearsandwich** [comment]
This change has been deployed!
