### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by fmrico** [ros2-gbp/ros2-gbp-github-org#184]
* Name of the new release team: plansys2
* Release repositories to add:
  * [popf](https://github.com/fmrico/popf.git)
    * [ ] There is an existing release repository which should be imported: https://github.com/fmrico/popf-release.git
  * [plansys2](https://github.com/PlanSys2/ros2_planning_system.git)
    * [ ] There is an existing release repository which should be imported: https://github.com/PlanSys2/ros2_planning_system-release.git

* Team members
  * [@fmrico](https://github.com/PlanSys2/ros2_planning_system/blob/master/plansys2_core/package.xml)

**Comment by nuclearsandwich** [comment]
@fmrico I see that https://github.com/IntelligentRoboticsLabs/ros2_planning_system-release.git used to be the url used for releases of ros2_planning_system. Can you please give a comment on the apparent transfer from the https://github.com/IntelligentRoboticsLabs/ so I can confirm everything is above board?

**Comment by fmrico** [comment]
Hi @nuclearsandwich 

Initially, ros2_planning_system was at https://github.com/IntelligentRoboticsLabs. Some months ago, I created the organization https://github.com/PlanSys2 to make independent my research group from all my planning projects. I moved the release repository to https://github.com/PlanSys2/ros2_planning_system-release. Now I want also to include also popf in this movement to ros2-GBP.

AFAIK, I have not been (and I shouldn't) using https://github.com/IntelligentRoboticsLabs/ros2_planning_system-release.git since the migration to https://github.com/PlanSys2

Best
Francisco

**Comment by nuclearsandwich** [comment]
Thanks for confirming, I just needed a public comment to confirm that the transfer was above board.

**Comment by fmrico** [comment]
Hi @nuclearsandwich 

I have just checked that these repositories don't exist yet. I thought that this issue would create them.
- https://github.com/ros-gbp/ros2_planning_system-release
- https://github.com/ros-gbp/popf-release

May you create them, or should I do anything else?

Thanks!!
