### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by jlblancoc** [ros2-gbp/ros2-gbp-github-org#185]
* Name of the new release team: borglab
* Release repositories to add:
  * [gtsam](https://github.com/borglab/gtsam/)
    * (No release repo yet, please create a new one for it)

* Team members
  * [@ProfFan](https://github.com/borglab/gtsam/blob/develop/package.xml)
  * [@jlblancoc](https://github.com/borglab/gtsam/blob/develop/package.xml)

**Comment by nuclearsandwich** [comment]
This change has been deployed!
