### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by 3473f** [ros2-gbp/ros2-gbp-github-org#202]
* Name of the new release team: 3473f
* Release repositories to add:
  * [ros2autodoc](https://github.com/3473f/ros2autodoc)

* Team members
  * [@3473f](https://github.com/3473f/ros2autodoc/blob/main/package.xml)

**Comment by nuclearsandwich** [comment]
Before release repositories are created for new repositories and packages, they should be submitted to the official rosdistro repository https://github.com/ros/rosdistro for naming review.
Guidelines for package naming are describe in REP-144: https://www.ros.org/reps/rep-0144.html

This section of the current contribution guideline is the best guide for the process so far https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#documentation-indexing some of the information may only apply to ROS 1 packages but opening a PR for source and doc entries for any ROS 2 distribution will be enough to trigger the naming review.

Please open the ros/rosdistro PR and link it in this issue. Once your package has been reviewed and index we can proceed with the release repository configuration.

Thanks!

**Comment by nuclearsandwich** [comment]
Hi @3473f are you still trying to prepare this package for release? Have you opened a PR to add the source entry?

**Comment by nuclearsandwich** [comment]
@3473f I am going to close this for now but please do re-open it when the above conditions are met!
