### ISSUE TITLE
Add new release repositories: rig_reconfigure

### ISSUE THREAD

**Issue by ottojo** [ros2-gbp/ros2-gbp-github-org#205]
* Name of the release team: [teamspatzenhirn](https://github.com/orgs/ros2-gbp/teams/teamspatzenhirn)

* Release repositories to add:
  * [rig_reconfigure](https://github.com/teamspatzenhirn/rig_reconfigure)

(rosdistro PR: https://github.com/ros/rosdistro/pull/36192)

**Comment by nuclearsandwich** [comment]
This change has been deployed!
