### ISSUE TITLE
Mirror existing Metro Robots release repositories

### ISSUE THREAD

**Issue by DLu** [ros2-gbp/ros2-gbp-github-org#235]
* Name of the release team: `metro_robots_team`

* Release repositories to add:
  * [polygon_ros](https://github.com/MetroRobots/polygon_ros)
    * [x] There is an existing release repository which should be imported: https://github.com/MetroRobots-release/polygon_ros-release
  * [color_util](https://github.com/MetroRobots/color_util)
    * [x] There is an existing release repository which should be imported: https://github.com/MetroRobots-release/color_util-release

This is not a pressing issue. 

Also, this is currently open: https://github.com/ros/rosdistro/pull/36709

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Comment by DLu** [comment]
Thanks!
