### ISSUE TITLE
Add new astuff_sensor_msgs release repo

### ISSUE THREAD

**Issue by icolwell-as** [ros2-gbp/ros2-gbp-github-org#253]
* Name of the release team: astuff

* Release repositories to add:
  * [astuff_sensor_msgs](https://github.com/astuff/astuff_sensor_msgs-release)
    * [ ] There is an existing release repository which should be imported: https://github.com/astuff/astuff_sensor_msgs-release

**Comment by nuclearsandwich** [comment]
This change has been deployed.
