### ISSUE TITLE
Add release team for https://github.com/Minipada/ros2_data_collection

### ISSUE THREAD

**Issue by Minipada** [ros2-gbp/ros2-gbp-github-org#257]
* Name of the new release team: minipada
* Release repositories to add:
  * https://github.com/Minipada/ros2_data_collection

* Team members
  * @minipada

**Comment by nuclearsandwich** [comment]
Hello @Minipada, before we create a release repository could you please open a PR on https://github.com/ros/rosdistro adding a source entry to one of the currently active ROS 2 distributions (Rolling or Humble would be best). This will ensure your packages undergo license and naming review before the release repository is created. Once open you can link the PR here and bump this request once it is merged.

**Comment by Minipada** [comment]
Thanks, I created this https://github.com/ros/rosdistro/pull/37289

**Comment by Minipada** [comment]
@nuclearsandwich It is merged

**Comment by nuclearsandwich** [comment]
This change has been deployed!
