### ISSUE TITLE
Add release team numsr

### ISSUE THREAD

**Issue by ngmor** [ros2-gbp/ros2-gbp-github-org#259]
* Name of the new release team: numsr
* Release repositories to add: None (for now, awaiting a rosdistro pull request)
* Team members
  * [@m-elwin](https://github.com/ngmor/catch_ros2/blob/36d5a629cf8f1a98b3ad02cc65690135cfb6b8ee/catch_ros2/package.xml#L10)
  * [@ngmor](https://github.com/ngmor/catch_ros2/blob/36d5a629cf8f1a98b3ad02cc65690135cfb6b8ee/catch_ros2/package.xml#L9)
  * [@hang-yin](https://github.com/ngmor/catch_ros2/blob/36d5a629cf8f1a98b3ad02cc65690135cfb6b8ee/catch_ros2/package.xml#L11)

**Comment by ngmor** [comment]
[Here](https://github.com/ros/rosdistro/pull/37305) is the PR for the rosdistro entry, which we eventually intend to release with bloom.

Edit: this PR is now closed and merged, I will be moving forward with releasing the package with bloom shortly using this release team.

**Comment by nuclearsandwich** [comment]
This change has been deployed!
