### ISSUE TITLE
Add new release repositories for MetroRobots

### ISSUE THREAD

**Issue by DLu** [ros2-gbp/ros2-gbp-github-org#260]
* Name of the release team: [metro_robots](https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/metro_robots.tf)

* Release repositories to add:
  * [social_nav_ros](https://github.com/MetroRobots/social_nav_ros)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/dac5ede8bee976579e83ce8cfe66c424d5dcfcf0/foxy/distribution.yaml#L6772)
  * [urdf_launch](https://github.com/MetroRobots/urdf_launch)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/dac5ede8bee976579e83ce8cfe66c424d5dcfcf0/foxy/distribution.yaml#L7470)
  * [classic_bags](https://github.com/MetroRobots/classic_bags)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/dac5ede8bee976579e83ce8cfe66c424d5dcfcf0/rolling/distribution.yaml#L684)

**Comment by nuclearsandwich** [comment]
This change has been deployed!
