### ISSUE TITLE
Update release team membership - ros_industrial.tf

### ISSUE THREAD

**Issue by hellantos** [ros2-gbp/ros2-gbp-github-org#269]
# Updates to ros_industrial.tf membership.

## New team members

* [@ipa-cmh](https://github.com/ros-industrial/ros2_canopen/blob/master/canopen/package.xml#L7)

Motivated by https://github.com/ros-industrial/ros2_canopen/issues/129

**Comment by nuclearsandwich** [comment]
FYI @Levi-Armstrong @marip8 are you okay with adding this repository here and granting @ipa-cmh release access to ros_industrial_cmake_boilerplate and stomp or should I create a separate release team?

**Comment by Levi-Armstrong** [comment]
I am fine with adding them

**Comment by marip8** [comment]
Yes, please do

**Comment by nuclearsandwich** [comment]
Thank you for confirming!
