### ISSUE TITLE
Add new release repositories: executive_smach

### ISSUE THREAD

**Issue by 130s** [ros2-gbp/ros2-gbp-github-org#275]
* Name of the release team:

Only @130s for now, no team. If someone can volunteer to join as a backup maintenance member that's great.

* Release repositories to add: 
  * [ros/executive_smach](https://github.com/ros/executive_smach)
    * ros/rosdistro source entry --> Requested https://github.com/ros/rosdistro/pull/37620

**Comment by 130s** [comment]
Honestly I didn't really understand what the issue template requires. Hope I've given all info requested...

**Comment by nuclearsandwich** [comment]
> Honestly I didn't really understand what the issue template requires. Hope I've given all info requested...

Thank you for your efforts to complete the template. You did provide all of the necessary information and completed the template successfully.

If you would be willing to comment on https://github.com/ros2-gbp/ros2-gbp-github-org/pull/125 and let me know which parts were confusing or difficult to follow, it would help me improve the templates. Thanks!

Once the Humble source entry has been approved and merged, I will merge and deploy #276 to fulfill this request.

**Comment by 130s** [comment]
Ok, posted feedback https://github.com/ros2-gbp/ros2-gbp-github-org/pull/125#pullrequestreview-1479941656!

I like the idea of using PR's view, even after merge, for review (as long as it won't create confusion) :)

**Comment by nuclearsandwich** [comment]
In case I get lost today, the deployment of this PR was delayed because I hit the 5000 request rate limit after a few successive terraform plans. I should be updating within an hour confirming successful deployment but it's possible (given that it's Saturday) that time will get away from me while waiting.

**Comment by nuclearsandwich** [comment]
This change has been deployed!
