### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by Dr-Nali** [ros2-gbp/ros2-gbp-github-org#277]
* Name of the new release team: this_is_a_test
* Release repositories to add:
  * [arduino_serial_test](https://github.com/Dr-Nali/arduino_serial_test)
    * [x] There is an existing release repository which should be imported: https://github.com/Dr-Nali/arduino_serial_test-release

* Team members
  * @Dr-Nali

**Comment by nuclearsandwich** [comment]
This PR and #278 do not contain links to valid source repositories and do not provide much information. If you have questions about this process please ask but due to the low effort and lack of valid source package links I am going to close these issues.
