### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by nasr-ali** [ros2-gbp/ros2-gbp-github-org#278]
* Name of the new release team: testing_team
* Release repositories to add:
  * [arduino-serial-test](https://github.com/nasr-ali/arduino-serial-test)
    * [x] There is an existing release repository which should be imported: https://github.com/nasr-ali/arduino-serial-test-release
* Team members
  * @nasr-ali

**Comment by nuclearsandwich** [comment]
Closing for reasons described in https://github.com/ros2-gbp/ros2-gbp-github-org/issues/277#issuecomment-1605647072
