### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by ShotaAk** [ros2-gbp/ros2-gbp-github-org#286]
# Updates to `rt-net` membership.

## New team members

* [@Kuwamai](https://github.com/rt-net/crane_plus/blob/a737d0fc514b02714d959e5929b8c5ead1f6174b/crane_plus_control/package.xml#L11)
* [@YusukeKato](https://github.com/rt-net/crane_plus/blob/a737d0fc514b02714d959e5929b8c5ead1f6174b/crane_plus_control/package.xml#L12)

**Comment by nuclearsandwich** [comment]
This change has been deployed!
