### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by deyouslamtec** [ros2-gbp/ros2-gbp-github-org#287]
# Updates to rplidar release membership.

## New team members

* [@deyouslamtec](https://github.com/slamtec/rplidar_ros/blob/ros2/package.xml#L9)

## Retiring team members

* [@allenh1](https://github.com/allenh1/rplidar_ros/blob/ros2/package.xml#L7)

The rplidar_ros package is currently maintained by allenh1, and the repository address is https://github.com/allenh1/rplidar_ros/tree/ros2. 
In the future, rplidar_ros will be maintained by Slamtec. The new repository address is https://github.com/Slamtec/rplidar_ros/tree/ros2.

@allenh1 Please be informed

**Comment by nuclearsandwich** [comment]
@deyouslamtec both of the above links point to the same repository. Is that a typo?
In spite of #238 I think that this separate implementation probably requires a completely independent release team and release repository. I'm going to confer with @tfoote next week to follow up.

**Comment by deyouslamtec** [comment]
@nuclearsandwich Thank you for reminding me. I mistyped the first repo. It has been corrected now.

**Comment by deyouslamtec** [comment]
@nuclearsandwich We have discussed how to handle the handover of rplidar_ros package in this [issue](https://github.com/ros/rosdistro/issues/37679#issuecomment-1606004819)

**Comment by nuclearsandwich** [comment]
This change has been deployed!
