### ISSUE TITLE
Add new release team for ROS 2 FlexBE

### ISSUE THREAD

**Issue by dcconner** [ros2-gbp/ros2-gbp-github-org#289]
* Name of the new release team: flexbe
* Release repositories to add:
 Submitted PR for naming review https://github.com/ros/rosdistro/pull/37823

**_Proposed_** names of release repos:
      url: https://github.com/ros2-gbp/flexbe_app-release.git
      url: https://github.com/ros2-gbp/flexbe_behavior_engine-release.git

There are already a ROS 1 release repos created:
  https://github.com/FlexBE/flexbe_app-release
  https://github.com/FlexBE/flexbe_behavior_engine-release

But I planned to create separate ones on the ros2-gbp site .

I'm listing them below for completeness, but not sure we want to import versus just create new.

  If there are any existing release repositories which should have their contents imported into the ros2-gbp organization, list and link to them here.
  Leave the checkbox _unchecked_. The ros2-gbp administrator will check the box when they have completed the repository import.
  -->
  * [flexbe_app](https://github.com/flexbe/flexbe_app.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L1541)
    * [ ] There is an existing release repository which should be imported: https://github.com/FlexBE/flexbe_app-release
  * [flexbe_behavior_engine](https://github.com/flexbe/flexbe_behavior_engine.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L1551)
    * [ ] There is an existing release repository which should be imported: https://github.com/FlexBE/flexbe_behavior_engine-release

* Team members
  * [@dcconner](https://github.com/FlexBE/flexbe_behavior_engine/blob/ros2-devel/flexbe_behavior_engine/package.xml#L10)
  * [@pschillinger](https://github.com/FlexBE/flexbe_behavior_engine/blob/ros2-devel/flexbe_behavior_engine/package.xml#L9)

**Comment by nuclearsandwich** [comment]
> I'm listing them below for completeness, but not sure we want to import versus just create new.

I think its entirely up to you. I'd propose either:
1. importing the existing release repo contents and using the ros2-gbp release repository for both Noetic and ROS 2 distributions. To prevent accidental pushes to the previous release repo it should be archived but not deleted.
OR
2. starting fresh repositories in ros2-gbp and using them just for ROS 2 while using the current repositories for Noetic.

The advantages of the first option are that you don't have to worry about mistargeted pushes at the expense of slight confusion that "ros2-gbp" is used for ROS Noetic releases. But there's no technical reason not to do so.

I've opened https://github.com/ros2-gbp/ros2-gbp-github-org/pull/293 and will wait to merge it or import release repositories pending your preference above and the merging of https://github.com/ros/rosdistro/pull/37823

**Comment by dcconner** [comment]
Would it be an option to combine by doing option 2, and then recreating  the noetic release   on ros2-gdp  vs. importing the entire history.  Then I can archive the old one after the changes take effect.

Otherwise, I'm inclined to just do option 2.

**Comment by dcconner** [comment]
@nuclearsandwich - Added rosdistro source link

**Comment by dcconner** [comment]
Is there anything missing that is preventing #293 from being merged so that I can prepare the release?

I have the naming approvals from rosdistro linked above:
    * https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L1541
    * https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L1551

**Comment by nuclearsandwich** [comment]
> Would it be an option to combine by doing option 2, and then recreating the noetic release on ros2-gdp vs. importing the entire history. Then I can archive the old one after the changes take effect.

What reason is there not to import the Noetic history?
Importing it is a small effort, basically after I create the repository in ros2-gbp I just run
```
git clone --mirror $OLD_REPO 
cd $OLD_REPO
git remote add ros2-gbp git@github.com:$(basename $(pwd))
git push --mirror ros2-gbp
```

Keeping the release history for noetic together is a much nicer experience for someone who wants to review the release history of the package.



> Is there anything missing that is preventing #293 from being merged so that I can prepare the release?

Nope with the links you mention we're now ready to proceed pending a decision on importing noetic history or starting fresh with ROS 2 releases only.

**Comment by dcconner** [comment]
I planned to import full history of noetic just not the obsolete branches

Let's roll with this plan.  Thanks.

**Comment by dcconner** [comment]
To clarify, my intent was to` git push ros2-gbp noetic` then create a new humble branch 

If that is not sufficient and you want to mirror the entire repo with obsolete branches before noetic, let me know.   I'd lean toward just doing option 2 in that case and only using this repo for ROS 2, but happy to comply with whatever you want to move this forward.

**Comment by dcconner** [comment]
@nuclearsandwich  ?

**Comment by dcconner** [comment]
Touching base on this again.  

There is an issue with flexbe_app release identified by @sloretz https://github.com/FlexBE/flexbe_app/issues/90 

I do NOT plan to push a flexbe_app release in the near term, but would like to get the humble release for flexbe_behavior_engine out the door.

**Comment by nuclearsandwich** [comment]
> I planned to import full history of noetic just not the obsolete branches

Got it. Thanks for the clarification. I think that a `--mirror` clone even if it pulls in some older distros is going to be the most reliable way to make sure each ref for the noetic releases is included. It's also usually the ros2-gbp admin's responsibility to perform the initial mirror push and I'd prefer to to keep the practice limited to either mirror push or brand new repo rather than doing something in-between.

**Comment by dcconner** [comment]
Whatever you suggest to move this forward.

> it's also usually the ros2-gbp admin's responsibility to perform the initial mirror push

I take "admin" to mean @nuclearsandwich or someone will handle the initial push then. 

Let's just mirror the flexbe_behavior_engine-release.  
The flexbe_app-release had issues, so we will start that one fresh at the appropriate time.

**Comment by nuclearsandwich** [comment]
#293 is being deployed now. Once it is I'll mirror flexbe_behavior_engine-release and report back here

> I take "admin" to mean @nuclearsandwich or someone will handle the initial push then.

Yep that's generally me although there are [others](https://github.com/ros2-gbp/ros2-gbp-github-org/blob/e7fae2f3c7664a224ad0a4590e27c018f518aa91/00-main.tf#L8-L14) in case something happens to me.

**Comment by nuclearsandwich** [comment]
This change has been deployed and github.com/ros2-gbp/flexbe_behavior_engine-release mirrors https://github.com/FlexBE/flexbe_behavior_engine-release

**Comment by dcconner** [comment]
@nuclearsandwich questions:
1) why is the default branch of new mirrored repo not "master"
   It seems odd to have a very old branch as default and not show the release history
2) why do I not have permission to change the default branch settings?

**Comment by nuclearsandwich** [comment]
> why is the default branch of new mirrored repo not "master"

This is a side effect of the fact that in git the 'default' branch is just the first one pushed. So when mirroring to an empty repository the first branch is often the lexicographically topmost one and thus becomes the default.

I've switched it to bloom's config branch which is `master`.


> why do I not have permission to change the default branch settings?

Release team members have `mantain` permission on GitHub to protect from unintended or malicious deletion of community resources and ensure that repository configuration changes are managed via these terraform scripts.
