### ISSUE TITLE
Add Kinova Robotics release team

### ISSUE THREAD

**Issue by moriarty** [ros2-gbp/ros2-gbp-github-org#291]
* Name of the new release team: kinova_robotics
* Release repositories to add: ros2_kortex-release
  

I am preparing to release a new repository and set of packages for ROS 2 that will be transferred to the kinovarobotics github organization.

  * ROS 2 version: https://github.com/PickNikRobotics/ros2_kortex
    * kortex_api
    * kortex_bringup
    * kortex_description
    * kortex_driver
    * kortex_moveit_config

Note, this is a ROS 2 re-implementation of an release of an existing ROS 1 repository.

**Edit: has been open sourced under PickNikRobotics will transfer ownership after initial debian releases and support**
~Unfortunately there repo is still private and ownership needs to be transferred before release. It is expected that this is finished within the next week.~

I am opening this issue to have the release team and release repository created now as we would like not have any delays. There are no new package names (minor typo move_it->moveit) other packages removed as we've been able to relay more on upstream ROS 2 Control.

  * ROS 1 version: https://github.com/Kinovarobotics/ros_kortex
    * kortex_api
    * kortex_control
    * kortex_description
    * kortex_driver
    * kortex_examples
    * kortex_move_it_config
  
* Team members
  * @moriarty PickNik Robotics [package.xml](https://github.com/PickNikRobotics/ros2_kortex/blob/22572c7668d2afe602aacf102cec1d55fec8a0aa/kortex_driver/package.xml#L7)
  * @felixmaisonneuve Kinova Robotics [package.xml](https://github.com/PickNikRobotics/ros2_kortex/blob/22572c7668d2afe602aacf102cec1d55fec8a0aa/kortex_driver/package.xml#L8)
  * @martinleroux Kinova Robotics [package.xml](https://github.com/PickNikRobotics/ros2_kortex/blob/22572c7668d2afe602aacf102cec1d55fec8a0aa/kortex_driver/package.xml#L9)

**Comment by nuclearsandwich** [comment]
> I am opening this issue to have the release team and release repository created now as we would like not have any delays. There are no new package names (minor typo move_it->moveit) other packages removed as we've been able to relay more on upstream ROS 2 Control.

I understand and appreciate the desire to be proactive. However, I don't find any occurrences (using `git grep`) of the terms `kinova` or `kortex` in [ros/rosdistro](https://github.com/ros/rosdistro) which means that these package names have not been reviewed previously and thus I think they should go through the complete current process which means that the source entry should be added to [ros/rosdistro](https://github.com/ros/rosdistro) in order to indicate that the repository and packages it contains have passed new package review.

In the meantime, I've opened #294 which will resolve this issue when the naming review is complete.

**Comment by nuclearsandwich** [comment]
> * @moriarty PickNik Robotics
> * @felixmaisonneuve Kinova Robotics
> * @martinleroux Kinova Robotics

When the source repository is public please update these to link with maintainer or author entries in the package source for transparency.

**Comment by moriarty** [comment]
@nuclearsandwich Thanks! sorry I didn't even realize ros_kortex had never been released via rosdistro.

There is combination long weekends and summer vacations Saint-Jean-Baptiste Day, then Canada Day and now Independence Day :upside_down_face: I was trying to get this finished and released before :sweat_smile:

**Comment by moriarty** [comment]
> > * @moriarty PickNik Robotics
> > * @felixmaisonneuve Kinova Robotics
> > * @martinleroux Kinova Robotics
> 
> When the source repository is public please update these to link with maintainer or author entries in the package source for transparency.

@nuclearsandwich the repository is now public, and I've added links to the maintainers. also tagged them in the commit that referenced this issue.

So if you can create the `ros_kortex-release` repository that would be great.

There is still some missing dependencies that need to land before I can fully bloom and release all the packages...

- [x] ros2_kortex -> picknik_controllers https://github.com/ros2-gbp/ros2-gbp-github-org/issues/283 https://github.com/ros2-gbp/ros2-gbp-github-org/pull/284
- [ ] ros2_kortex -> ros2_robotiq_gripper https://github.com/ros2-gbp/ros2-gbp-github-org/issues/299
- [ ] ros2_robotiq_gripper -> serial now cxx_serial https://github.com/wjwwood/cxx_serial/issues/1

**Comment by nuclearsandwich** [comment]
This change has been deployed!
