### ISSUE TITLE
Add new release repositories

### ISSUE THREAD

**Issue by moriarty** [ros2-gbp/ros2-gbp-github-org#299]
* Name of the release team: picknik

* Release repositories to add: ros2_robotiq_gripper-release

  * [ros2_robotiq_gripper](https://github.com/PickNikRobotics/ros2_robotiq_gripper)
    * [ros/rosdistro source entry] https://github.com/ros/rosdistro/pull/37857

I've just submitted the PR adding the source entry into rosdistro.
package names:
 - robotiq_controllers
 - robotiq_description
 - robotiq_driver
 
 @MarqRazz and I from PickNik #281 will be maintaining this release along with the picknik_controllers #284 
 And the Robotiq gripper is the default gripper for the Kinova arm #291

**Comment by MarqRazz** [comment]
I'm really sorry @nuclearsandwich but I missed my window to accept the invite to the `ros2-gbp`. Could you please send another one?

**Comment by nuclearsandwich** [comment]
> I'm really sorry @nuclearsandwich but I missed my window to accept the invite to the `ros2-gbp`. Could you please send another one?

Yes it will send out when I do this afternoon's terraform deploy, which I'll note on this issue.

**Comment by nuclearsandwich** [comment]
This change has been deployed!
