### ISSUE TITLE
Add release team ros_event_camera

### ISSUE THREAD

**Issue by berndpfrommer** [ros2-gbp/ros2-gbp-github-org#302]
* Name of the new release team: ros_event_camera
* Release repositories to add:
  * [metavision_driver](https://github.com/ros-event-camera/metavision_driver)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/bf80e138b4fd32fd12f4ae396831562f45575de1/rolling/distribution.yaml#L2554)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/bf80e138b4fd32fd12f4ae396831562f45575de1/humble/distribution.yaml#L3099)
  * [event_camera_msgs](https://github.com/ros-event-camera/event_camera_msgs)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/bf80e138b4fd32fd12f4ae396831562f45575de1/rolling/distribution.yaml#L1198)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/bf80e138b4fd32fd12f4ae396831562f45575de1/humble/distribution.yaml#L1444)
* Team members
  * [@berndpfrommer](https://github.com/ros-event-camera/metavision_driver/blob/c7ec5f84bd9688e87e32ff83d6df64e577c3469a/package.xml#L7)
  * @k-chaney

**Comment by nuclearsandwich** [comment]
This change has been deployed!
