### ISSUE TITLE
Add new release repositories

### ISSUE THREAD

**Issue by tylerjw** [ros2-gbp/ros2-gbp-github-org#305]
* Name of the release team: picknik

* Release repositories to add:
  * [picknik_ros_vendor](https://github.com/PickNikRobotics/picknik_ros_vendor)

**Comment by nuclearsandwich** [comment]
@tylerjw thanks for opening the issue, before we create release repositories we'd like new repositories to have source entries added to ros/rosdistro so the packages go through license and REP-144 naming review.

I did a spot check of the contents and it looks like this is vendoring catch2, which is already available in Debian/Ubuntu, but may still requrie vendoring for other platforms.

**Comment by clalancette** [comment]
There's been no response to this in a long time, so I'm going to close this out.  Feel free to reopen when we have gone through a naming review.
