### ISSUE TITLE
Add release team for Ouster

### ISSUE THREAD

**Issue by Samahu** [ros2-gbp/ros2-gbp-github-org#308]
* Name of the new release team: ouster
* Release repositories to add:
  
  * ouster-ros-release: the ouster-ros-release is for [ouster-ros/iron](https://github.com/ouster-lidar/ouster-ros/blob/ros2/ouster-ros)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/9c23c70f8a9dc8afe5a6b14f73708fe258300097/iron/distribution.yaml#L3500)
    * [ ] There is an existing release repository which should be imported: http://www.github.com/ouster-lidar/ouster-ros-release

* Team members
  * @Samahu

**Comment by Samahu** [comment]
I am wondering if we could use the team instead of having to mention each individual member by name. Is that possible?

**Comment by nuclearsandwich** [comment]
> I am wondering if we could use the team instead of having to mention each individual member by name. Is that possible?

It isn't possible for a GitHub team from another organization to be used, so I'll need a list of maintainer usernames to complete the release team. When updating team membership you can either open issues or send pull requests to update the membership list in this repository.

**Comment by nuclearsandwich** [comment]
@tfoote from the discussion on https://github.com/ros/rosdistro/pull/38253 it sounds like there is implicit REP-144 naming approval for the incoming packages and I can proceed even though these packages have not yet had a source entry merged.

**Comment by nuclearsandwich** [comment]
> * Name of the new release team: ouster-release-team

The best name for this team is probably simply `ouster` since every issue here creates a release team, the `release-team` in the name is redundant.

**Comment by Samahu** [comment]
Ok, I have updated the release team name (to your recommendation and updated team members list.

**Comment by Samahu** [comment]
rosdistro Pull request was merged: https://github.com/ros/rosdistro/pull/38253#event-10142477298. The release repo still points to the location on **ouster-lidar** org instead of **ros2-gbp**. I was waiting on this to be issue to act on importing the release repository before I would change the location. But I believe we should be able to update the location of the release in a following pull request to rosdistro once the release repo has been imported.

**Comment by tfoote** [comment]
> @tfoote from the discussion on https://github.com/ros/rosdistro/pull/38253 it sounds like there is implicit REP-144 naming approval for the incoming packages and I can proceed even though these packages have not yet had a source entry merged.

Yes this is a maintainer transition more than new packages.

**Comment by Samahu** [comment]
Steven Macenski originally developed a package for ROS2 that interacts with Ouster sensors. Ouster had its own ROS1 driver which I later ported to ROS2 with shared code base between ROS1 and ROS2. Ouster wants to have its official driver be distributed through ROS2 build starting with ROS2 Iron. So the code base is different but I made sure to have build some compatibility towards the version Steve provided for previous ros2 distros. So I am not sure if you can consider it simply transition of the maintainer or not.

**Comment by Samahu** [comment]
I have added the rosdistro source link to the description of the issue [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/9c23c70f8a9dc8afe5a6b14f73708fe258300097/iron/distribution.yaml#L3500)

**Comment by nuclearsandwich** [comment]
This change has been deployed.

**Comment by Samahu** [comment]
Thank you, much appreciated it!
