### ISSUE TITLE
Add new release repositories for ouster_ros package

### ISSUE THREAD

**Issue by Samahu** [ros2-gbp/ros2-gbp-github-org#315]
* Name of the release team: ouster-release-team

* Release repositories to add: ouster-ros-release
  
  * [ouster-ros-release](https://github.com/ouster-lidar/ouster-ros-release)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/pull/38253)
    * [ ] There is an existing release repository which should be imported: https://github.com/ouster-lidar/ouster-ros-release

**Comment by Samahu** [comment]
Linking the release team addition request: https://github.com/ros2-gbp/ros2-gbp-github-org/issues/308

**Comment by nuclearsandwich** [comment]
I am going to close this and consolidate the request into #308 which I'll close when both the release team and the release repository are added.
