### ISSUE TITLE
Add 4 new release repositories for Metro Robots

### ISSUE THREAD

**Issue by DLu** [ros2-gbp/ros2-gbp-github-org#318]
* Name of the release team: [metro_robots](https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/metro_robots.tf)

* Release repositories to add: 
  * [metrics_msgs](https://github.com/MetroRobots/metrics_msgs.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/66407c7e305a83531ab7bf602cade6f06bbb053a/humble/distribution.yaml#L3177-L3182)
  * [metro_gazebo_plugins](https://github.com/MetroRobots/metro_gazebo_plugins.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/66407c7e305a83531ab7bf602cade6f06bbb053a/humble/distribution.yaml#L3183-L3188)
  * [the_navigation_gauntlet](https://github.com/MetroRobots/the_navigation_gauntlet.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/0b3102b04c630b6da008a0a249246951d125c0ad/humble/distribution.yaml#L7503-L7507)
  * [metro_nav](https://github.com/MetroRobots/metro_nav.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/1778246d21399eaf2e78b7b147eb60f07c8728f5/humble/distribution.yaml#L3189-L3194)

**Comment by DLu** [comment]
The *three* repositories we need are `metrics_msgs`, `metro_gazebo_plugins`, `the_navigation_gauntlet` and `metro_nav`. Wait, no....Amongst the release repositories we need are `fear`, `surprise`, and `fanatical_devotion_to_the_pope`

**Comment by DLu** [comment]
Ok, finally all up to date.

**Comment by nuclearsandwich** [comment]
This change has been deployed.

**Comment by DLu** [comment]
Thanks !!
