### ISSUE TITLE
issue #324 has not been resolved

### ISSUE THREAD

**Issue by berndpfrommer** [ros2-gbp/ros2-gbp-github-org#327]
I believe the repositories requested in issue #324 have not been added, yet the issue has been closed. Please look into this, thanks!
https://github.com/ros2-gbp/ros2-gbp-github-org/issues/324

**Comment by nuclearsandwich** [comment]
Thanks for opening the issue. There was a deployment problem which I didn't catch. The change has now been deployed and the repositories are created. You should be able to access them as soon as you accept the invitation to the ros2-gbp organization.

If you would please confirm access and close this issue once you have that would be appreciated!

**Comment by berndpfrommer** [comment]
Works now, thanks!
