### ISSUE TITLE
Add release team: Dexory

### ISSUE THREAD

**Issue by nachovizzo** [ros2-gbp/ros2-gbp-github-org#342]
* Name of the new release team: dexory
* Release repositories to add:

  * [ament-black](https://github.com/botsandus/ament_black.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/pull/38736)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

* Team members
  * [@nachovizzo](https://github.com/botsandus/ament_black/blob/d813287e4c6fe0e4c4c477b88f73ccb3370c2b71/ament_black/package.xml#L11C1-L12C1)

**Comment by tfoote** [comment]
From https://github.com/ros/rosdistro/pull/38736  This appears to be hijacking maintainership of the package. @nachovizzo Did you talk to @Timple about taking over maintenance of this package? I don't see any documented communications about this. Initial release

**Comment by tfoote** [comment]
There's agreement to transfer maintenance here

https://github.com/ros/rosdistro/pull/38736#issuecomment-1759301547

**Comment by nuclearsandwich** [comment]
This change has been deployed!
