### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by stefanscherzinger** [ros2-gbp/ros2-gbp-github-org#348]
* Name of the new release team: sick_safevisionary
* Release repositories to add:
  
  * [sick_safevisionary_base](https://github.com/SICKAG/sick_safevisionary_base)
  * [sick_safevisionary_ros2](https://github.com/SICKAG/sick_safevisionary_ros2)

* Team members
  * [@stefanscherzinger](https://github.com/SICKAG/sick_safevisionary_ros2/blob/df5f57b781b3cbb79088713d4ac0c41a57bdd2de/sick_safevisionary_driver/package.xml#L8)
  * [@MGBla](https://github.com/SICKAG/sick_safevisionary_ros2/blob/df5f57b781b3cbb79088713d4ac0c41a57bdd2de/sick_safevisionary_driver/package.xml#L7)
  * [@lienhjoSICKAG](https://github.com/SICKAG/sick_safevisionary_ros2/blob/df5f57b781b3cbb79088713d4ac0c41a57bdd2de/sick_safevisionary_driver/package.xml#L9)

**Comment by nuclearsandwich** [comment]
This change has been deployed!
