### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by nlamprian** [ros2-gbp/ros2-gbp-github-org#349]
* Name of the new release team: nlamprian
* Release repositories to add:
  
  * [gazebo_video_monitors](https://github.com/nlamprian/gazebo_video_monitors)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/pull/38794/commits/67f4a6866c4692bdf9c0e217dd1b2db0f336e6e3)

* Team members
  * [@nlamprian](https://github.com/nlamprian/gazebo_video_monitors/blob/ros2/gazebo_video_monitors/package.xml#L10)

**Comment by nuclearsandwich** [comment]
This change has been deployed!
