### ISSUE TITLE
Update release team membership [pal_robotics]

### ISSUE THREAD

**Issue by saikishor** [ros2-gbp/ros2-gbp-github-org#35]
# Updates to pal_robotics membership.

## New team members

* @saikishor
* @jordan-palacios
* @lucamarchionni
You can find our access levels here: https://github.com/pal-robotics/backward_ros/commits/foxy-devel

**Comment by saikishor** [comment]
Hello from @pal-robotics team,

Could you add all the above list of members to the list here: https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/pal_robotics.tf?. It would make us easier to proceed with the releases of `backward_ros` package.

Thank you,

**Comment by nuclearsandwich** [comment]
#36 has now been deployed!

**Comment by saikishor** [comment]
Hello @nuclearsandwich,

Thank you so much!
