### ISSUE TITLE
mobile_catkin_modules_build_development_tools

### ISSUE THREAD

**Issue by RonaldsonBellande** [ros2-gbp/ros2-gbp-github-org#352]
* Name of the release team: Ronaldson Bellande

* Release repositories to add: https://github.com/Application-UI-UX/mobile_catkin_modules_build_development_tools
* https://github.com/ros2-gbp/ros2-gbp-github-org/pull/339/commits/a715f9c933ffcf4bbfeb73063ef49146d3225c5f

**Comment by nuclearsandwich** [comment]
Resolved by #339.

**Comment by nuclearsandwich** [comment]
This change has been deployed!
