### ISSUE TITLE
mobile_message_service_generator

### ISSUE THREAD

**Issue by RonaldsonBellande** [ros2-gbp/ros2-gbp-github-org#361]
Name of the release team: Ronaldson Bellande

Release repositories to add: https://github.com/Application-UI-UX/mobile_message_service_generator

https://github.com/ros2-gbp/ros2-gbp-github-org/pull/360/files

**Comment by RonaldsonBellande** [comment]
For the Team of mobile_message_service_generator-release and for mobile_catkin_modules_build_development_tools-release. I'm a member and would need to be a maintainer. As I can't do anything related to branch management.

**Comment by nuclearsandwich** [comment]
@RonaldsonBellande before release repositories can be created, can you please submit your package for documentation and/or source indexing in ros/rosdistro according to the contributing guidelines here: https://github.com/ros/rosdistro/blob/master/CONTRIBUTING.md#documentation-indexing

This will ensure your package undergoes REP-144 naming convention review as well as standard license checks. Once the rosdistro index has been updated, we can proceed with your release team.

**Comment by RonaldsonBellande** [comment]
https://github.com/ros/rosdistro/pull/39079

**Comment by clalancette** [comment]
Closing this one as we don't have agreement on the package name.
