### ISSUE TITLE
Add new release repositories for rt-net

### ISSUE THREAD

**Issue by YusukeKato** [ros2-gbp/ros2-gbp-github-org#362]
* Name of the release team: rt-net

* Release repositories to add:
  
  * [raspimouse_sim](https://github.com/rt-net/raspimouse_sim)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L5120-L5124)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

**Comment by YusukeKato** [comment]
I don't know how to create a Pull Request only for source entry using `bloom`. Therefore, I created the PR manually.

https://github.com/ros/rosdistro/pull/38915

**Comment by YusukeKato** [comment]
I have added the source entry.

**Comment by nuclearsandwich** [comment]
This change has been deployed.
