### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by RoBeau** [ros2-gbp/ros2-gbp-github-org#363]
# Updates to Boeing membership.

## New team members
[@btra-jc ](https://github.com/brta-jc)
[@derme302](https://github.com/derme302)

**Comment by nuclearsandwich** [comment]
Both individuals are already members of the release team. However it appears that they did not accept the invitation to join before it expired. An additional invitation will be sent out a new deployment shortly. They must accept the invitations within 7 days. https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/boeing.tf#L4-L5

**Comment by nuclearsandwich** [comment]
These invites have been resent.
