### ISSUE TITLE
add release repository for libcaer_driver

### ISSUE THREAD

**Issue by berndpfrommer** [ros2-gbp/ros2-gbp-github-org#365]
* Name of the release team: ros-event-camera

* Release repositories to add:
  
  * [ros-event-camera/libcaer_driver](https://github.com/ros-event-camera/libcaer_driver.git)
    * [libcaer_driver](https://github.com/ros/rosdistro/blob/7bd100ab29bc6e8d5f134bd1941d83381c005876/rolling/distribution.yaml#L2451C18-L2451C18)

**Comment by nuclearsandwich** [comment]
This change has been deployed.
