### ISSUE TITLE
Humanoid Robot Intelligence Control System Tools

### ISSUE THREAD

**Issue by RonaldsonBellande** [ros2-gbp/ros2-gbp-github-org#377]
Name of the release team: Ronaldson Bellande

Release repositories to add: https://github.com/Robotics-Sensors/humanoid_robot_intelligence_control_system_tools

https://github.com/ros2-gbp/ros2-gbp-github-org/pull/376

**Comment by nuclearsandwich** [comment]
Please consolidate these issues into one with https://github.com/ros2-gbp/ros2-gbp-github-org/issues/367#issuecomment-1817272775
