### ISSUE TITLE
mobile_message_service_generator-release  Update release team membership

### ISSUE THREAD

**Issue by RonaldsonBellande** [ros2-gbp/ros2-gbp-github-org#384]
# Updates to maintainer of mobile_message_service_generator-release.

## Retiring team members

* [RonaldsonBellande](https://github.com/ros2-gbp/mobile_catkin_modules_build_development_tools-release/commits/main)
Update RonaldsonBellande from member to maintainer in mobile_message_service_generator-release team.

**Comment by clalancette** [comment]
Closing this one as we don't have agreement on the source repository.
