### ISSUE TITLE
Add release team MOCAP4ROS2

### ISSUE THREAD

**Issue by fmrico** [ros2-gbp/ros2-gbp-github-org#385]
* Name of the new release team: mocap4ros2
* Release repositories to add:
  * [mocap_msgs](https://github.com/MOCAP4ROS2-Project/mocap_msgs)
  * [mocap](https://github.com/MOCAP4ROS2-Project/mocap)

* Team members
  * [@fmrico](https://github.com/MOCAP4ROS2-Project/mocap_msgs/blob/master/package.xml)
  * @jmguerreroh

**Comment by fmrico** [comment]
Hi @nuclearsandwich!!  

Any advance with this? We would like to release the packages soon :disappointed_relieved:, and we would like to have the release repos created by this issue.

Thanks!! Francisco

**Comment by berndpfrommer** [comment]
I'm in the same boat.
https://discourse.ros.org/chat/c/-/11/1382

**Comment by clalancette** [comment]
One problem with this request for a release team is that the set of packages in https://github.com/MOCAP4ROS2-Project/mocap have not undergone a REP-144 naming review.  So what I'm going to suggest here is that you open a source-only PR to https://github.com/ros/rosdistro adding in the repository.  Assuming it passes the naming review, we can then go ahead and create the release repository and teams here.

**Comment by nuclearsandwich** [comment]
@fmrico apologies for the delay here, as mentioned by other reviewers the naming review needs to be completed first. It sounds like consensus is coming so once the package names are updated and the source entry is re-submitted we can move forward here.

**Comment by nuclearsandwich** [comment]
@fmrico I'm going to close this issue for now as it's been some time since and the rosdistro PRs are closed pending new package names. We can re-open this issue or open a new one for future packages.
