### ISSUE TITLE
Add new release repository for libcaer

### ISSUE THREAD

**Issue by berndpfrommer** [ros2-gbp/ros2-gbp-github-org#386]
* Name of the release team: ros-event-camera

* Release repositories to add:
* [libcaer](https://github.com/ros-event-camera/libcaer)
    * [libcaer (humble)](https://github.com/ros/rosdistro/blob/a0086de3bf81a78566e2d1a2a4385641e524ad19/humble/distribution.yaml#L3029)
    * [libcaer (iron)](https://github.com/ros/rosdistro/blob/a0086de3bf81a78566e2d1a2a4385641e524ad19/iron/distribution.yaml#L2567)
    * [libcaer (rolling)](https://github.com/ros/rosdistro/blob/a0086de3bf81a78566e2d1a2a4385641e524ad19/rolling/distribution.yaml#L2495)

**Comment by clalancette** [comment]
Presumably the release team will just contain @berndpfrommer .

This looks good to me.
