### ISSUE TITLE
Add new release repository for myactuator_rmd

### ISSUE THREAD

**Issue by 2b-t** [ros2-gbp/ros2-gbp-github-org#387]
* Name of the release team: cerberus

* Release repositories to add:
  * [2b-t/myactuator_rmd](https://github.com/2b-t/myactuator_rmd)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/a0086de3bf81a78566e2d1a2a4385641e524ad19/humble/distribution.yaml#L3812-L3821)

**Comment by clalancette** [comment]
Presumable the only member of the cerberus team will be @2b-t .

This looks good to me.
