### ISSUE TITLE
Add new release repositories

### ISSUE THREAD

**Issue by fmauch** [ros2-gbp/ros2-gbp-github-org#39]
* Name of the release team: universal_robots_team

* Release repositories to add:
  * [ur_msgs](https://github.com/ros-industrial/ur_msgs)
    * The existing release repository will still be used for ROS1
  * [Universal_Robots_ROS2_Driver](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver)

Thank you very much!

**Comment by nuclearsandwich** [comment]
@fmauch these are both new release repositories correct?

**Comment by fmauch** [comment]
Yes, exactly.
