### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by cubicleguy** [ros2-gbp/ros2-gbp-github-org#391]
* Name of the new release team: ess_imu_driver2_team   
* Release repositories to add:
  
  * [ess_imu_driver2](https://github.com/cubicleguy/ess_imu_driver2)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L1592C1-L1592C1)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>
  * ...

* Team members
  * [@cubicleguy](https://github.com/cubicleguy/ess_imu_driver2/blob/humble/package.xml)
  * ...

**Comment by clalancette** [comment]
This looks good to me.
