### ISSUE TITLE
Add release team: sync_parameter_server_team

### ISSUE THREAD

**Issue by Tacha-S** [ros2-gbp/ros2-gbp-github-org#395]
* Name of the new release team:  sync_parameter_server_team
* Release repositories to add:
  
  * [sync_parameter_server](https://github.com/Tacha-S/sync_parameter_server)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/31f950c0a4bb159f9fa1947096ed2e4cefd85d55/humble/distribution.yaml#L7954-L7958)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

* Team members
  * [@Tacha-S](https://github.com/Tacha-S/sync_parameter_server/blob/0ea0b7c2203b3ac47c563418883c24b6d40e1d4a/package.xml#L7)

**Comment by clalancette** [comment]
This looks good to me.
