### ISSUE TITLE
Add "pangolin" release team

### ISSUE THREAD

**Issue by christian-rauch** [ros2-gbp/ros2-gbp-github-org#396]
* Name of the new release team: `pangolin`
* Release repositories to add:
  
  * [Pangolin](https://github.com/stevenlovegrove/Pangolin)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/6bc055ea8f82b320b3234d9341bb537f79463e21/rolling/distribution.yaml#L3655-L3659)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

* Team members
  * @christian-rauch (https://github.com/stevenlovegrove/Pangolin/blob/master/package.xml)

**Comment by clalancette** [comment]
One minor thing that I think would help here is to add yourself to the maintainers list in https://github.com/stevenlovegrove/Pangolin/blob/master/package.xml (that would just give us additional confidence that you are indeed one of the maintainers).

But that isn't blocking here, so this looks good to me.
