### ISSUE TITLE
Add release team: Black Coffee Robotics

### ISSUE THREAD

**Issue by ggupta9777** [ros2-gbp/ros2-gbp-github-org#403]
* Name of the new release team: black_coffee_robotics
* Release repositories to add:
  
  * [bcr_bot](https://github.com/blackcoffeerobotics/bcr_bot.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L671-L685)
    * [ ] There is an existing release repository which should be imported: https://github.com/blackcoffeerobotics/bcr_bot_ros2-release.git
* Team members
  * [@ggupta9777](https://github.com/blackcoffeerobotics/bcr_bot/blob/ros2/package.xml#L7)
  * [@D-1shu](https://github.com/blackcoffeerobotics/bcr_bot/blob/ros2/package.xml#L8)

**Comment by clalancette** [comment]
This looks good to me.
