### ISSUE TITLE
Add new release repositories

### ISSUE THREAD

**Issue by methylDragon** [ros2-gbp/ros2-gbp-github-org#41]
* Name of the release team: 
acceleration_wg

* Release repositories to add:
  * adaptive_component-release, for:
    * [adaptive_component](https://github.com/ros-acceleration/adaptive_component)

Associated PR created: https://github.com/ros2-gbp/ros2-gbp-github-org/pull/40

**Comment by nuclearsandwich** [comment]
Resolved by #40.

@methylDragon for the future there's no need to create an issue if you already have a pull request prepared. But please do use the issue template as a template for PRs as well :bow:
