### ISSUE TITLE
Update default branch of ament_black-release repo

### ISSUE THREAD

**Issue by nachovizzo** [ros2-gbp/ros2-gbp-github-org#426]
Not sure where/who to ask. But https://github.com/ros2-gbp/ament_black-release has a `main` branch (apparently created by hand, by me) which I would like to remove, and make `master` the default branch. This is because `bloom` use the `master` branch instead of `main`.

I tired to do it but I have no permissions

**Comment by clalancette** [comment]
I've gone ahead and done this manually, which is all we can do for now.

That said, this is only a cosmetic change; it won't actually change any functionality.

I'll close this out for now.
