### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by vicmassy** [ros2-gbp/ros2-gbp-github-org#431]
* Name of the new release team: umdlife_team
* Release repositories to add:
  
  * [psdk_ros2](https://github.com/umdlife/psdk_ros2)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/5facb7789e11b110438182675b660280ee25d60c/humble/distribution.yaml#L5321)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

* Team members
  * [@biancabnd] (https://github.com/umdlife/psdk_ros2/blob/26e5043d7cc980438f3aaad80730f21b7c21f688/psdk_wrapper/package.xml#L7)
  * [@vicmassy]
  (https://github.com/umdlife/psdk_ros2/blob/26e5043d7cc980438f3aaad80730f21b7c21f688/psdk_wrapper/package.xml#L8)

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Comment by vicmassy** [comment]
Thank you!
