### ISSUE TITLE
Add new release repositories

### ISSUE THREAD

**Issue by adityapande-1995** [ros2-gbp/ros2-gbp-github-org#432]
* Name of the release team:  ros2-team

* Release repositories to add:

  * [FIRST_REPOSITORY](https://github.com/adityapande-1995/linux_isolate_process)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/45c0f14b78c0c91c1d6698ac2bf0eab6c4b64d55/rolling/distribution.yaml#L2646-L2650)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

**Comment by nuclearsandwich** [comment]
This change has been deployed!
