### ISSUE TITLE
Add release team 'ros4hri'

### ISSUE THREAD

**Issue by severin-lemaignan** [ros2-gbp/ros2-gbp-github-org#439]
* Name of the new release team: ros4hri
* Release repositories to add:
  
  * [hri_msgs](https://github.com/ros4hri/hri_msgs)
    * [ros/rosdistro source entry](https://github.com/ros4hri/hri_msgs.git)
    * https://github.com/ros/rosdistro/pull/39751
    * [ ] There is an existing release repository which should be imported: https://github.com/ros4hri/hri_msgs-release.git

There will be several additional repo to be added to this team,as we release ROS4HRI on ROS 2. I can either submit them to `rosdistro` and add them to this issue, or we first create the release team with only `hri_msgs`, and I'll create additional issues for the subsequent package additions?

* Team members
  * [@severin-lemaignan](https://github.com/ros4hri/hri_msgs/blob/humble-devel/package.xml#L7)

**Comment by nuclearsandwich** [comment]
> There will be several additional repo to be added to this team,as we release ROS4HRI on ROS 2. I can either submit them to `rosdistro` and add them to this issue, or we first create the release team with only `hri_msgs`, and I'll create additional issues for the subsequent package additions?

I'll process this issue now and you can open an additional one for the remaining repositories. Depending on how many repositories and how long naming review takes, let's aim for around ~week between batches as needed.

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Comment by severin-lemaignan** [comment]
brilliant, thanks!
We are still in the midst of porting and testing the full ros4hri pipelines -> I'll probably need a few more weeks before pushing the next repos (`human_description` and `libhri`)
