### ISSUE TITLE
Add new release repository for apriltag_detector

### ISSUE THREAD

**Issue by berndpfrommer** [ros2-gbp/ros2-gbp-github-org#440]
* Name of the release team: ros-misc-utilities

* Release repositories to add:

  * [apriltag_detector](https://github.com/ros-misc-utilities/apriltag_detector/)
    * [humble source entry](https://github.com/ros/rosdistro/blob/f0d0df77a7ad5d4728b17ca78a88656d7bbe0e80/humble/distribution.yaml#L467)
    * [iron source entry](https://github.com/ros/rosdistro/blob/f0d0df77a7ad5d4728b17ca78a88656d7bbe0e80/iron/distribution.yaml#L361)
    * [rolling source entry](https://github.com/ros/rosdistro/blob/f0d0df77a7ad5d4728b17ca78a88656d7bbe0e80/rolling/distribution.yaml#L361)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

**Comment by nuclearsandwich** [comment]
This change has been deployed!
