### ISSUE TITLE
Add a new release repository for unitree_ros

### ISSUE THREAD

**Issue by PedroS235** [ros2-gbp/ros2-gbp-github-org#441]
* Name of the release team: snt-arg

* Release repositories to add:
  * [unitree_ros](https://github.com/snt-arg/unitree_ros)
    * I have created a [PR](https://github.com/ros/rosdistro/pull/39857#issuecomment-1934281070) on rosdistro. Waiting it to be merged.

**Comment by nuclearsandwich** [comment]
> * Waiting it to be merged.

Projects must be merged in rosdistro before release repositories are created.

**Comment by PedroS235** [comment]
Hey @nuclearsandwich,

Thanks for reviewing the issue. 
I am currently stuck due to license restrictions to add the repo to rosdistro. I am in the process to change to a license that fits rosdistro requirements, thus it will take some time for me to change it. 

Would it be fine for this issue to be opened until it gets uploaded to rosdistro?

**Comment by nuclearsandwich** [comment]
> Would it be fine for this issue to be opened until it gets uploaded to rosdistro?

Yep, this issue can remain parked until the upstream PR is resolved which I see could be shortly.

**Comment by PedroS235** [comment]
Hey @nuclearsandwich,

The PR has now been merged. However, I am not too sure where I can get this rosdistro source link. Would it be these:
- [iron](https://github.com/ros/rosdistro/blob/91f78edebe2e15c21647d12dc196ebc5c9b28f8a/iron/distribution.yaml#L7754?)
- [humble](https://github.com/ros/rosdistro/blob/91f78edebe2e15c21647d12dc196ebc5c9b28f8a/humble/distribution.yaml#L9231)

**Comment by nuclearsandwich** [comment]
This change has been deployed!
