### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by Ryanf55** [ros2-gbp/ros2-gbp-github-org#449]
# Updates to `grid_map_team` membership.

## New team members

* [@ryanf55](https://github.com/ANYbotics/grid_map/blob/e332abbcc4b50ebea432d5a40d3609bf5cb52fa1/grid_map/package.xml#L9)

**Comment by nuclearsandwich** [comment]
This change has been merged but not yet deployed as I'm away from power at the moment and don't have enough charge to deploy. I'll be deploying this change later today and will update the issue when completed.

**Comment by nuclearsandwich** [comment]
This change has been deployed.
