### ISSUE TITLE
Add new release repositories: etsi_its_messages

### ISSUE THREAD

**Issue by lreiher** [ros2-gbp/ros2-gbp-github-org#463]
Two of our ROS release repositories have just been moved to ros2-gbp, see [here](https://github.com/ros/rosdistro/pull/40024) and [here](https://github.com/ros/rosdistro/pull/40025). I'd like to move a third release repository to ros2-gbp.

Also, one question: since the release repositories in here are only used for ROS2, am I right to assume that we should still keep releasing ROS1 updates to those repositories to the existing release repositories in our organization?

* Name of the release team: [ika_rwth_aachen_team](https://github.com/ros2-gbp/ros2-gbp-github-org/pull/458)

* Release repositories to add:
  
  * [ika-rwth-aachen/etsi_its_messages](https://github.com/ika-rwth-aachen/etsi_its_messages)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L1728)
    * [ ] There is an existing release repository which should be imported: [ika-rwth-aachen/etsi_its_messages-release](https://github.com/ika-rwth-aachen/etsi_its_messages-release)

**Comment by nuclearsandwich** [comment]
This change has been deployed!
