### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by jonbinney** [ros2-gbp/ros2-gbp-github-org#464]
# Updates to ros2_core membership.

## New team members

* [@jonbinney](https://github.com/ros/filters/blob/3f4ee5a5fe3a8ae4886c1b11b6a2597b6e5c4a04/package.xml#L11)

## Retiring team members

* None

Note: I occasionally release the filters package on ros2 and would like to do a release now, see [this issue](https://github.com/ros/filters/issues/72). ros2-core seems to give far access to far more repos than I need though. I'm also fine with asking one of the existing ros2_core team members to do a release each time it is needed. @tfoote thoughts?

**Comment by tfoote** [comment]
The core team is a shortcut to make sure that we not drop anything. But spreading out the responsibility is better. I'd suggest adding a release team specific to filters for you to be in.

**Comment by jonbinney** [comment]
I'll close this and add a new issue for creating the team.

**Comment by jonbinney** [comment]
Issue for creating the team here: https://github.com/ros2-gbp/ros2-gbp-github-org/issues/465
