### ISSUE TITLE
Add release team for filters

### ISSUE THREAD

**Issue by jonbinney** [ros2-gbp/ros2-gbp-github-org#465]
* Name of the new release team: filters
* Release repositories to add:
  * [filters](https://github.com/ros/filters)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/2015deacc57af0b7a10779554666cc58994356b3/rolling/distribution.yaml#L1465)
    * [x ] There is an existing release repository which should be imported: https://github.com/ros2-gbp/filters-release
* Team members
  * [@tfoote](https://github.com/ros/filters/blob/3f4ee5a5fe3a8ae4886c1b11b6a2597b6e5c4a04/package.xml#L10)
  * [@jonbinney](https://github.com/ros/filters/blob/3f4ee5a5fe3a8ae4886c1b11b6a2597b6e5c4a04/package.xml#L11)

**Comment by jonbinney** [comment]
This is blocking https://github.com/ros/filters/issues/72

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Comment by jonbinney** [comment]
Thank you!
