### ISSUE TITLE
Add release team for niwcpac

### ISSUE THREAD

**Issue by xydesa** [ros2-gbp/ros2-gbp-github-org#466]
* Name of the new release team: niwcpac
* Release repositories to add:
  * [rqt_dotgraph](https://github.com/niwcpac/rqt_dotgraph)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/master/rolling/distribution.yaml#L6265)
* Team members
  * [@xydesa](https://github.com/niwcpac/rqt_dotgraph/blob/main/package.xml#L7)
  * [@denewiler](https://github.com/niwcpac/rqt_dotgraph/blob/main/package.xml#L8)
  * [@gregtkogut](https://github.com/niwcpac/rqt_dotgraph/blob/main/package.xml#L9)

**Comment by denewiler** [comment]
I have a rosdistro branch ready to go that adds a new package to rosdistro distribution.yaml files if we need to do that first.

https://github.com/ros/rosdistro/compare/master...tdenewiler:rosdistro:rqt-dotgraph

**Comment by nuclearsandwich** [comment]
@denewiler @xydesa before the release team is created, the PR to rosdistro which adds the `source` (and optionally `doc`) entries should be created so that the package can undergo license and naming review. The `release` stanza should be omitted from the manually created PR and added by using the `bloom` utility to create the release once the release repository is created.

Once the linked comparison has been opened as a PR and merged into ros/rosdistro please update this request.

**Comment by xydesa** [comment]
@nuclearsandwich Thanks for letting us know. FYI the [ROS2 documentation](https://docs.ros.org/en/humble/How-To-Guides/Releasing/First-Time-Release.html) makes it seem like we needed a release team first and the ticket template in here is ambiguous on that count. Which is why I made this PR first.

**Comment by nuclearsandwich** [comment]
> FYI the [ROS2 documentation](https://docs.ros.org/en/humble/How-To-Guides/Releasing/First-Time-Release.html) makes it seem like we needed a release team first and the ticket template in here is ambiguous on that count. Which is why I made this PR first.

It's a bit labyrinthine but the documentation for [Creating a release repository](https://docs.ros.org/en/humble/How-To-Guides/Releasing/Release-Team-Repository.html#create-a-new-release-repository) points out that "If your repository is new to the ROS community, you should first open a pull request on [ros/rosdistro](https://github.com/ros/rosdistro) adding a source entry for your repository."

Building better tooling for this workflow (or optimizing it away) is definitely in my goals for the future.

**Comment by xydesa** [comment]
https://github.com/ros/rosdistro/pull/40169

has been merged. ticket description updated.

**Comment by tdenewiler** [comment]
I know you are busy working on the Jazzy release (and we are excited for that). Just adding a comment here to see if there is time to create this new release team. Thanks!

**Comment by nuclearsandwich** [comment]
This change has been deployed.

> I know you are busy working on the Jazzy release (and we are excited for that). Just adding a comment here to see if there is time to create this new release team. Thanks!

Thanks for your patience and understanding!
