### ISSUE TITLE
Having to manually create a README.md file before bloom release

### ISSUE THREAD

**Issue by ijnek** [ros2-gbp/ros2-gbp-github-org#47]
@nuclearsandwich
Thank you for getting around to creating the release repositories.

Following bloom instructions, it fails to push to the remote release repositories because they are empty:

```
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master

Cannot push to remote release repository.
Hint: If you just typed in your username/password and you have two-factor authentication,see:
  http://wiki.ros.org/bloom/Tutorials/GithubManualAuthorization
```

It is just a matter of having an empty README.md in the release repository before performing the release, but the suggestion given to ``git push --set-upstream origin master`` in the error is misleading. (can't do much about that)

Is it possible to ensure that the release repositories are initialised with a blank README.md when they are created, or should we add that to the instructions for package maintainers?

**Comment by nuclearsandwich** [comment]
@ijnek I think that part of the problem could be that bloom's configuration is hard-coded to use a master branch but this is no longer the default branch created in a fresh GitHub repository. I don't think that an empty readme needs to be created there just needs to be a master branch but since there's no straightforward way to create a branch on GitHub without first creating a commit, that's one way to do it.

I do think that Bloom should be updated here to support this case since it is the new normal. If you could share the instructions that you followed and the error message you got in full we can probably figure out how to make bloom push to an empty git repository correctly.

**Comment by tfoote** [comment]
I think it might make sense to updated bloom to try main, if that fails try master, and if that fails then throw an error that no branch exists please create one.

**Comment by ijnek** [comment]
The empty README.md is what's currently suggested in [bloom/FirstTimeRelease](http://wiki.ros.org/bloom/Tutorials/FirstTimeRelease), 

> Create a new repository in the github organization or on the github user of your choice. By convention you should name it as your package name with the -release suffix. So for the ros_comm repository the corresponding release repository is called ros_comm-release. Note: When creating your github.com repository, check the box **Initialize this repository with a README.md,** this way it starts out as a valid git repo. Bloom will later fill this file with information about released versions.

I agree with adopting Github's rename from ``master`` to ``main`` in the bloom scripts, but I don't think the issue we're facing here is about matching the branch names between ros2-gbp and what bloom expects. I haven't had an issue initializing a repo with a main branch, and performing a bloom-release on it. Bloom seems to just create a new master branch and push it to Github.

What's required is to have the repository initialised, with any branch name. Three options I can think of ensuring the Github repo is initialized:
1. Initialise the Github repo in bloom, if it's not initialized
2. Prompt user to intialize the Github repo from the bloom script if not initialized
3. Initialise the Github repo when it's created in ros2-gbp

@nuclearsandwich I'm not sure if you're manually creating the release repositories, or auto-generating them with a script, but if you can initialize the release repositories when creating them, I think options 3 is best. If that's not possible, probably option 1.

**Comment by nuclearsandwich** [comment]
> I think it might make sense to updated bloom to try main, if that fails try master, and if that fails then throw an error that no branch exists please create one.

It's not trivial to support multiple options for the config branch in Bloom based on  reviewing the commit history around the transition from `bloom` to `master` earlier in bloom's development. It can't be an either/or thing but something we have to transition for every bloom repository. I'm not saying that it can't or shouldn't be done but it's a bigger transition to undertake and make sure that bloom maintains release integrity.
