### ISSUE TITLE
Add release team for grid_map_geo

### ISSUE THREAD

**Issue by Ryanf55** [ros2-gbp/ros2-gbp-github-org#471]
* Name of the new release team: `grid_map_geo_team`
* Release repositories to add:
  
  * [FIRST_REPOSITORY](SOURCE URL)
    * [ros/rosdistro source entry](LINK TO SOURCE FIELD IN ROS/ROSDISTRO)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>
  * [SECOND REPOSITORY](SOURCE URL)
    * [ros/rosdistro source entry](LINK TO SOURCE FIELD IN ROS/ROSDISTRO)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>
  * ...
^ Please create a repository for us

* Team members
  * [@ryanf55](https://github.com/ethz-asl/grid_map_geo/blob/02189d61cdc30c384e59a76ba1d044e002c39ba9/package.xml#L8)
  * [@Jaeyoung-Lim](https://github.com/ethz-asl/grid_map_geo/blob/02189d61cdc30c384e59a76ba1d044e002c39ba9/package.xml#L7)

Ticket: See https://github.com/ethz-asl/grid_map_geo/issues/50

**Comment by nuclearsandwich** [comment]
@Ryanf55 can you please follow the guide here: https://docs.ros.org/en/humble/How-To-Guides/Releasing/Release-Team-Repository.html#create-a-new-release-repository and open a PR on https://github.com/ros/rosdistro so that these packages undergo REP-144 naming and license review before release repositories are created.

**Comment by Ryanf55** [comment]
> @Ryanf55 can you please follow the guide here: https://docs.ros.org/en/humble/How-To-Guides/Releasing/Release-Team-Repository.html#create-a-new-release-repository and open a PR on https://github.com/ros/rosdistro so that these packages undergo REP-144 naming and license review before release repositories are created.

Done!

**Comment by nuclearsandwich** [comment]
Indexed as of https://github.com/ros/rosdistro/pull/40449

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Comment by Ryanf55** [comment]
Can we also add Jay to the [release team](https://github.com/orgs/ros2-gbp/teams/grid_map_geo)? He would like the ability to do releases too.
