### ISSUE TITLE
Update release team membership - ros_industrial.tf

### ISSUE THREAD

**Issue by ipa-vsp** [ros2-gbp/ros2-gbp-github-org#480]
# Updates to ros_industrial.tf membership.

## New team members

* [ipa-vsp](https://github.com/ros-industrial/ros2_canopen/blob/c6e2ab3d604d6599237eace3b1f52bfe00160bea/canopen/package.xml#L8)

Motivation: https://github.com/ros-industrial/ros2_canopen/issues/273

**Comment by nuclearsandwich** [comment]
Since the requesting user @ipa-vsp has linked their maintainer tag above and is clearly committing to the upstream repository I'm treating that as sufficient evidence that this is an upstream maintainer.

FYI current ros_industrial members: @Levi-Armstrong, @hellantos, @marip8.

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Comment by ipa-vsp** [comment]
@nuclearsandwich Thank you!
