### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by jordan-palacios** [ros2-gbp/ros2-gbp-github-org#482]
# Updates to pal_robotics team membership.

## New team members

* [@Noel215](https://github.com/pal-robotics/pal_statistics/blob/humble-devel/pal_statistics/package.xml#L8)

## Retiring team members

* [@v-lopez ](https://github.com/pal-robotics/pal_statistics/commit/17b012505be99279a4e5d9d7429cdcb132504683#diff-f9d91a6784b725ff32281061a0a4a4dea0c945f25357429093fda2d8f832cc78)

**Comment by nuclearsandwich** [comment]
This change has been deployed!
