### ISSUE TITLE
Add new release repository: apriltag_mit

### ISSUE THREAD

**Issue by berndpfrommer** [ros2-gbp/ros2-gbp-github-org#493]
* Name of the release team: ros-misc-utilities (look for "misc_utilities.tf")

  * [apriltag_mit](https://github.com/ros-misc-utilities/apriltag_mit)
    * [humble source entry](https://github.com/ros/rosdistro/blob/09f9f734f0700e2b1683d88765e7bcd64b1e2bdf/humble/distribution.yaml#L480)

**Comment by nuclearsandwich** [comment]
This change has been deployed. This is the first release repository to be created with a default template (#499) which should smooth out recent issues with GitHub release repositories and bloom. Please open a new issue on https://github.com/ros2-gbp/ros2-gbp-github-org if you have any problems. Thanks!
