### ISSUE TITLE
Add new release repository for rmw_zenoh

### ISSUE THREAD

**Issue by Yadunund** [ros2-gbp/ros2-gbp-github-org#494]
* Name of the release team: ros_team

* Release repositories to add:
  
  * [rmw_zenoh](https://github.com/ros2/rmw_zenoh.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/pull/40677)

**Comment by nuclearsandwich** [comment]
Once the linked rosdistro source PR has merged, this request can be processed.

**Comment by Yadunund** [comment]
@nuclearsandwich the rosdistro PR has been merged!

**Comment by nuclearsandwich** [comment]
This change has been deployed.
