### ISSUE TITLE
Add release team (for kuka drivers)

### ISSUE THREAD

**Issue by Svastits** [ros2-gbp/ros2-gbp-github-org#505]
* Name of the new release team: kuka
* Release repositories to add:

  * [kuka_external_control_sdk](https://github.com/kroshu/kuka-external-control-sdk)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/ae6a26d3d3ddf3a0f7acab8ca8c7a7f2b6377196/humble/distribution.yaml#L3154C1-L3163C22)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>
  * [kuka_robot_descriptions](https://github.com/kroshu/kuka_robot_descriptions)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/ae6a26d3d3ddf3a0f7acab8ca8c7a7f2b6377196/humble/distribution.yaml#L3164C1-L3173C22)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>
  * [kuka_drivers](https://github.com/kroshu/kuka_drivers)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/ae6a26d3d3ddf3a0f7acab8ca8c7a7f2b6377196/humble/distribution.yaml#L3144C1-L3153C22)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

* Team members
  * [@Svastits](https://github.com/kroshu/kuka_drivers/blob/44c5a6fce0e1efd0482be00f8372a58442462117/kuka_drivers/package.xml#L6)
  * [@kovacsge11](https://github.com/kroshu/kuka_drivers/blob/44c5a6fce0e1efd0482be00f8372a58442462117/kuka_drivers/package.xml#L7)
  * [@VX792](https://github.com/kroshu/kuka_drivers/blob/44c5a6fce0e1efd0482be00f8372a58442462117/kuka_drivers/package.xml#L8)

**Comment by nuclearsandwich** [comment]
This change has been deployed.
