### ISSUE TITLE
Add new Release Repositories for ndt_omp and fast_gicp

### ISSUE THREAD

**Issue by hridaybavle** [ros2-gbp/ros2-gbp-github-org#509]
* Name of the release team: 

snt_arg

* Release repositories to add:
  
    * [fast_gicp](https://github.com/SMRT-AIST/fast_gicp)
        * [ros/rosdistro source entry ] --> https://github.com/ros/rosdistro/pull/40807

    * [ndt_omp](https://github.com/koide3/ndt_omp)
        * [ros/rosdistro source entry ] --> https://github.com/ros/rosdistro/pull/40808

**Comment by hridaybavle** [comment]
Hello pull requests are already merged into master. Could you create the release repos please.

**Comment by nuclearsandwich** [comment]
This change has been deployed.
