### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by AndreasKuhner** [ros2-gbp/ros2-gbp-github-org#514]
* Name of the new release team: franka_robotics 
* Release repositories to add:
  
  * [franka_description](https://github.com/frankaemika/franka_description.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/f2adfe56b1ef4184dd7e5d6de7eff6a7cff6b0e7/humble/distribution.yaml#L2208C3-L2208C21)

* Team members
  * [@BarisYazici](https://github.com/BarisYazici)
  * [@AndreasKuhner](https://github.com/AndreasKuhner)
  * [@kmohyeldin](https://github.com/kmohyeldin)
  * [@winkma](https://github.com/winkma)
  * [@gomezgu](https://github.com/gomezgu)

**Comment by AndreasKuhner** [comment]
What would be the next step? :)

**Comment by nuclearsandwich** [comment]
> What would be the next step? :)

Thank you for the patience here. I've been backed up on some other infrastructure work and hadn't had a chance to work down this review queue. #521 will resolve this request once merged and deployed in the next couple of hours.

**Comment by nuclearsandwich** [comment]
This change has been deployed.
