### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by dlangenkamp-avt** [ros2-gbp/ros2-gbp-github-org#515]
* Name of the new release team: alliedvision
* Release repositories to add:
  
  * [vimbax_ros2_driver](https://github.com/alliedvision/vimbax_ros2_driver.git)
    * ros/rosdistro source entry -> PR: https://github.com/ros/rosdistro/pull/41095

* Team members
  * @dlangenkamp-avt
  * @fklostermann
  * @khoepke

**Comment by nuclearsandwich** [comment]
This change has been deployed.
