### ISSUE TITLE
Add new release repositories: libcaer_vendor

### ISSUE THREAD

**Issue by berndpfrommer** [ros2-gbp/ros2-gbp-github-org#517]
* Name of the release team: ros-event-camera
* Release repositories to add:
  * [libcaer_vendor](https://github.com/ros-event-camera/libcaer/)
    * [humble source entry](https://github.com/ros/rosdistro/blob/72eeaec8e84f147feed051717ed324edc006a60c/humble/distribution.yaml#L3515)
    * [iron source entry](https://github.com/ros/rosdistro/blob/72eeaec8e84f147feed051717ed324edc006a60c/iron/distribution.yaml#L2822)
    * [jazzy source entry](https://github.com/ros/rosdistro/blob/72eeaec8e84f147feed051717ed324edc006a60c/jazzy/distribution.yaml#L2924)
    * [rolling source entry](https://github.com/ros/rosdistro/blob/72eeaec8e84f147feed051717ed324edc006a60c/rolling/distribution.yaml#L2951)

**Comment by nuclearsandwich** [comment]
This change has been deployed.
