### ISSUE TITLE
Add beluga release team

### ISSUE THREAD

**Issue by hidmic** [ros2-gbp/ros2-gbp-github-org#518]
* Name of the new release team: beluga
* Release repositories to add:
  
  * [Ekumen-OS/beluga](https://github.com/Ekumen-OS/beluga)
    * [noetic source entry](https://github.com/ros/rosdistro/blob/33229c39fb48111a754c18c67a7e85e558fad9a7/noetic/distribution.yaml#L572-L581)
    * [humble source entry](https://github.com/ros/rosdistro/blob/33229c39fb48111a754c18c67a7e85e558fad9a7/humble/distribution.yaml#L795-L804)
    * [iron source entry](https://github.com/ros/rosdistro/blob/33229c39fb48111a754c18c67a7e85e558fad9a7/iron/distribution.yaml#L617-L626)
    * [jazzy source entry](https://github.com/ros/rosdistro/blob/33229c39fb48111a754c18c67a7e85e558fad9a7/jazzy/distribution.yaml#L655-L664)

* Team members
  * @nahueespinosa ([maintainer](https://github.com/Ekumen-OS/beluga/blob/71d3f0cae0588ce2fed1beb847999bf08e2fcf69/beluga_amcl/package.xml#L12))
  * @glpuga ([maintainer](https://github.com/Ekumen-OS/beluga/blob/71d3f0cae0588ce2fed1beb847999bf08e2fcf69/beluga_amcl/package.xml#L9))
  * @hidmic ([maintainer](https://github.com/Ekumen-OS/beluga/blob/71d3f0cae0588ce2fed1beb847999bf08e2fcf69/beluga_amcl/package.xml#L11))

**Comment by hidmic** [comment]
Friendly ping @nuclearsandwich perhaps?

**Comment by mjcarroll** [comment]
Howdy @hidmic! I think that @nuclearsandwich usually does a pass over ros2-gbp on Fridays.

**Comment by hidmic** [comment]
Cool, thanks @mjcarroll @nuclearsandwich. I've added #520 so we can (hopefully) do it all in one go. Let me know if and how I can help.

**Comment by nuclearsandwich** [comment]
This change has been deployed.
