### ISSUE TITLE
Add new release repository: openeb_vendor

### ISSUE THREAD

**Issue by berndpfrommer** [ros2-gbp/ros2-gbp-github-org#526]
* Name of the release team: ros-event-camera

* Release repositories to add:
  * [openeb_vendor](https://github.com/ros-event-camera/openeb_vendor)
    * [source entry for humble](https://github.com/ros/rosdistro/blob/4bf5b935d47c08d4343474f60ba848d146f3101a/humble/distribution.yaml#L5135)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

**Comment by nuclearsandwich** [comment]
This change has been deployed.
