### ISSUE TITLE
Add new release repositories for situational_graphs_msgs

### ISSUE THREAD

**Issue by hridaybavle** [ros2-gbp/ros2-gbp-github-org#529]
* Name of the release team: 

snt_arg

* Release repositories to add:

     - [situtational_graphs_msgs](https://github.com/snt-arg/situational_graphs_msgs)

     - [ros/rosdistro source entry ](https://github.com/ros/rosdistro/pull/40801) --> merged

**Comment by nuclearsandwich** [comment]
This change has been deployed.
