### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by torydebra** [ros2-gbp/ros2-gbp-github-org#537]
* Name of the new release team: hhcm_iit 
* Release repositories to add:
  
  * [nicla_vision_ros](https://github.com/ADVRHumanoids/nicla_vision_ros)
    * [ros/rosdistro source entry](LINK TO SOURCE FIELD IN ROS/ROSDISTRO)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>
  * [nicla_vision_ros2](https://github.com/ADVRHumanoids/nicla_vision_ros2)
    * [ros/rosdistro source entry](LINK TO SOURCE FIELD IN ROS/ROSDISTRO)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

* Team members
  * [@torydebra](https://github.com/ADVRHumanoids/nicla_vision_ros2/blob/f4a5c0a6ce85d8f27a9f72e7cea7f201cdd67fb5/package.xml#L14)
  * [@damigas](https://github.com/ADVRHumanoids/nicla_vision_ros2/blob/f4a5c0a6ce85d8f27a9f72e7cea7f201cdd67fb5/package.xml#L15)

**Comment by torydebra** [comment]
Related rosdistro PR
https://github.com/ros/rosdistro/pull/41486

**Comment by torydebra** [comment]
Hi, the PR https://github.com/ros/rosdistro/pull/41486 has been merged

**Comment by nuclearsandwich** [comment]
@torydebra I didn't add a repository for `nicla_vision_ros` in #563 since we don't require release repositories for ROS 1 packages to be in this or any other specific organization. If you'd like to have one in this org for ease, then please open another issue and add `nicla_vision_ros` to the ROS Noetic distribution.

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Comment by torydebra** [comment]
That's fine, thanks!
