### ISSUE TITLE
Add new release repositories

### ISSUE THREAD

**Issue by alsora** [ros2-gbp/ros2-gbp-github-org#538]
* Name of the release team: `irobot_education`

* Release repositories to add:
 `create3_examples` repo: https://github.com/iRobotEducation/create3_examples/tree/humble
reviewed here https://github.com/ros/rosdistro/pull/41397

**Comment by alsora** [comment]
Hi, any update on this?

**Comment by nuclearsandwich** [comment]
Thanks for your patience here. This change has been deployed.
