### ISSUE TITLE
Add new release repositories

### ISSUE THREAD

**Issue by SteveMacenski** [ros2-gbp/ros2-gbp-github-org#539]
* Name of the release team: navigation

* Release repositories to add:
  * [nav2_minimal_turtlebot_simulation](https://github.com/ros-navigation/nav2_minimal_turtlebot_simulation)
    * [jazzy rosdistro PR](https://github.com/ros/rosdistro/pull/41511)
    * [rolling rosdistro PR](https://github.com/ros/rosdistro/pull/41510)
    * [ ] There is an existing release repository which should be imported: https://github.com/ros-navigation/nav2_minimal_turtlebot_simulation-release

**Comment by SteveMacenski** [comment]
@nuclearsandwich how should I go about moving that existing release repo over to this org - should I add you to the existing repo to do the transfer or should I myself? I just don’t want to make a move like that without the OK and that I have the appropriate permissions.

**Comment by nuclearsandwich** [comment]
> should I add you to the existing repo to do the transfer or should I myself? I just don’t want to make a move like that without the OK and that I have the appropriate permissions.

Thanks for checking in. We generally don't bother with transferring release repositories. I usually use a mirror clone and push to update the ros2-gbp repository.

```
git clone --mirror <previous release repo>
git remote add ros2-gbp git@github.com:ros2-gbp/$(basename pwd)
git push --mirror ros2-gbp
```

I also recommend archiving the original release repo so that the artifacts remain available but the repository is not accidentally used instead of the ros2-gbp one.

**Comment by SteveMacenski** [comment]
Done. Should I manually update the rosdistro file or does part of the automation here do that? https://github.com/ros/rosdistro/blob/master/rolling/distribution.yaml#L3840-L3854
