### ISSUE TITLE
Add hebi release team

### ISSUE THREAD

**Issue by cwbollinger** [ros2-gbp/ros2-gbp-github-org#540]
* Name of the new release team: hebi
* Release repositories to add:
  
  * [HebiRobotics/hebi_cpp_api_ros](https://github.com/HebiRobotics/hebi_cpp_api_ros.git)
    * [humble source entry](https://github.com/ros/rosdistro/blob/ed9f58248989c439f504fdd9a859cb656e72146a/humble/distribution.yaml#L2767)

* Team members
  * @cwbollinger ([maintainer](https://github.com/HebiRobotics/hebi_cpp_api_ros/blob/df7ea0222b24283b944752569edbcbf4db792a93/package.xml#L7))
  * @hr1799 ([maintainer](https://github.com/HebiRobotics/hebi_cpp_api_ros/blob/df7ea0222b24283b944752569edbcbf4db792a93/package.xml#L8))

**Comment by nuclearsandwich** [comment]
This change has been deployed.
