### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by StefanFabian** [ros2-gbp/ros2-gbp-github-org#541]
* Name of the new release team: tuda_sim
* Release repositories to add:
  * [ros_babel_fish](https://github.com/LOEWE-emergenCITY/ros2_babel_fish)
    * [rosdep/jazzy](https://github.com/ros/rosdistro/blob/master/jazzy/distribution.yaml#L6365)
  * [qml_ros2_plugin](https://github.com/StefanFabian/qml_ros2_plugin)
    * [rosdep/jazzy](https://github.com/ros/rosdistro/blob/master/jazzy/distribution.yaml#L5159)
* Team members
  * [@StefanFabian](https://github.com/LOEWE-emergenCITY/ros2_babel_fish/blob/jazzy/ros2_babel_fish/package.xml#L11)
  * [@Martin-Oehler](https://github.com/tu-darmstadt-ros-pkg/image_projection/blob/master/image_projection/package.xml#L9)
  * [@JoLichtenfeld](https://github.com/tu-darmstadt-ros-pkg/hector_grid_map_compression/blob/main/hector_grid_map_compression/package.xml#L10)

**Comment by nuclearsandwich** [comment]
Hi @StefanFabian, can you please update this issue to list the release repositories that this team will be responsible for managing?

We need at least one repository before we create a release team.

**Comment by StefanFabian** [comment]
Okay, I must admit I'm a bit confused.
According to the [docs](https://docs.ros.org/en/jazzy/How-To-Guides/Releasing/First-Time-Release.html) I need to be part of a release team before I can create a new release repository.
We do have our own release org from ROS 1 times (see [hector_slam release repository](https://github.com/tu-darmstadt-ros-pkg-gbp/hector_slam-release)) but as I understood it, we should now use this org for release repos.

So, if I understand correctly, I should first make an "Add New Release Repositories" issue contrary to what the docs say?

**Comment by nuclearsandwich** [comment]
Sorry for the confusion. The intended path through that documentation is that you'd start a new release team following https://docs.ros.org/en/jazzy/How-To-Guides/Releasing/Release-Team-Repository.html#start-a-new-release-team and open this issue. What's missing based on the template is the release repositories that this team will own. It's not required that the release repositories exist already. By way of example, if your plan is to release `hector_slam` for ROS 2, you would list `hector_slam`.

This new release team template adds both the team and repositories, whereas the "Add new release repositories" template is for adding new repositories to an existing team.

**Comment by StefanFabian** [comment]
Ah okay, thank you for the explanation.
I have added the two repositories I intend to release right now.

**Comment by StefanFabian** [comment]
Just fyi I don't get a notification if only a label is added. Not sure if this is due to my settings or generally the case.
I've added rosdistro links to the entries for both repos.

**Comment by nuclearsandwich** [comment]
This change has been deployed.

**Comment by StefanFabian** [comment]
Thank you, while you're currently at it, could you add another release repo for this package that was also just added to rosdistro:
* [hector_rviz_overlay](https://github.com/tu-darmstadt-ros-pkg/hector_rviz_overlay)
  * [rosdistro/jazzy](https://github.com/ros/rosdistro/blob/master/jazzy/distribution.yaml#L2575)
  
  I can also create a new repo issue if you'd prefer that route.
