### ISSUE TITLE
Add new release repository flex_sync

### ISSUE THREAD

**Issue by berndpfrommer** [ros2-gbp/ros2-gbp-github-org#544]
* Name of the release team: ros-misc-utilities

* Release repositories to add:
  * [flex_sync](https://github.com/ros-misc-utilities/flex_sync)
    * [ros/rosdistro source entry (humble)](https://github.com/ros/rosdistro/blob/1e7d9f567c1ea81b37dad217823d800d56f75989/humble/distribution.yaml#L2129)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

**Comment by nuclearsandwich** [comment]
This change has been deployed.
