### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by brow1633** [ros2-gbp/ros2-gbp-github-org#545]
* Name of the new release team: network_bridge 
* Release repositories to add:
  
  * [network_bridge](https://github.com/brow1633/network_bridge)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/pull/41576/files)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

* Team members
  * [@brow1633](https://github.com/brow1633/network_bridge/blob/main/package.xml)

**Comment by nuclearsandwich** [comment]
This change has been deployed.
