### ISSUE TITLE
Add new release repositories [rosx_introspection]

### ISSUE THREAD

**Issue by facontidavide** [ros2-gbp/ros2-gbp-github-org#546]
* Name of the release team:  can I piggyback on the **plotjuggler_team** , since this library is primarily used there?

Otherwise I can request a new release team.

* Release repositories to add: 

  * [rosx_introspection](https://github.com/facontidavide/rosx_introspection)
    * ros/rosdistro source entry: see https://github.com/ros/rosdistro/pull/41657

**Comment by facontidavide** [comment]
Hi, now that https://github.com/ros/rosdistro/pull/41657 was merged, I think we can move on with this.

Shall I propose a new release team with me as user?

**Comment by nuclearsandwich** [comment]
Thanks for the patience here @facontidavide we can use plotjuggler team.

**Comment by nuclearsandwich** [comment]
This change has been deployed.
