### ISSUE TITLE
Add release team for asyncapi_gencpp, hatchbed_common, log_view, opensw, opensw_ros

### ISSUE THREAD

**Issue by malban** [ros2-gbp/ros2-gbp-github-org#558]
* Name of the new release team: hatchbed
* Release repositories to add:
  * [asyncapi_gencpp](https://github.com/hatchbed/asyncapi_gencpp)
    * [rolling/asyncapi_gencpp](https://github.com/ros/rosdistro/blob/master/rolling/distribution.yaml#L498)
  * [hatchbed_common](https://github.com/hatchbed/hatchbed_common)
    * [rolling/hatchbed_common](https://github.com/ros/rosdistro/blob/master/rolling/distribution.yaml#L2385)
  * [log_view](https://github.com/hatchbed/log_view)
    * [rolling/log_view](https://github.com/ros/rosdistro/blob/master/rolling/distribution.yaml#L3148)
    * [x] There is an existing release repository which should be imported: https://github.com/hatchbed/log_view-release
  * [opensw](https://github.com/hatchbed/opensw)
    * [rolling/opensw](https://github.com/ros/rosdistro/blob/master/rolling/distribution.yaml#L4216)
  * [opensw_ros](https://github.com/hatchbed/opensw_ros)
    * [rolling/opensw_ros](https://github.com/ros/rosdistro/blob/master/rolling/distribution.yaml#L4226)

Team Members:
  * @malban
  * @pjreed

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Comment by malban** [comment]
@nuclearsandwich 

Should the contents of https://github.com/hatchbed/log_view-release get imported to https://github.com/ros2-gbp/log_view-release?

Also, should I have permissions to the release repo?

I get this error when running bloom:
```
==> git remote -v
origin	git@github.com:ros2-gbp/log_view-release.git (fetch)
origin	git@github.com:ros2-gbp/log_view-release.git (push)
==> git push origin master --dry-run
ERROR: Permission to ros2-gbp/log_view-release.git denied to malban.
fatal: Could not read from remote repository..
```

I might be doing something wrong, but I set up an access token in `~/.config/bloom` and setup `~/.gitconfig` to always use my ssh credentials as recommended here: http://wiki.ros.org/bloom/Tutorials/GithubManualAuthorization
