### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by boitumeloruf** [ros2-gbp/ros2-gbp-github-org#559]
* Name of the new release team: fraunhofer_iosb_ars
* Release repositories to add:
  * [camera_aravis2](https://github.com/FraunhoferIOSB/camera_aravis2.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/1b07b45419478a4857080ec47fcbbc0da8482726/jazzy/distribution.yaml#L816)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

* Team members
  * [@boitumeloruf](https://github.com/FraunhoferIOSB/camera_aravis2/blob/main/camera_aravis2/package.xml)
  * @rapzag
  * @thomasemter
  * @jpetereit

**Comment by nuclearsandwich** [comment]
This change has been deployed!
