### ISSUE TITLE
Add new release repositories

### ISSUE THREAD

**Issue by padhupradheep** [ros2-gbp/ros2-gbp-github-org#568]
* Name of the release team: Neobotix

* Release repositories to add:
  
  * [neo_nav2_bringup](https://github.com/neobotix/neo_nav2_bringup)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/30e3197c9cc9a39642e3a73c814ed0d5bb8af9fd/iron/distribution.yaml#L3923)

**Comment by nuclearsandwich** [comment]
This change has been deployed.
