### ISSUE TITLE
Add new release repositories

### ISSUE THREAD

**Issue by CAcarADI** [ros2-gbp/ros2-gbp-github-org#569]
* Name of the release team: analogdevicesinc_tmcl

* Release repositories to add: 
  
  * [adi_tmc_coe](https://github.com/analogdevicesinc/adi_tmc_coe)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/pull/42126) -> Merged

**Comment by nuclearsandwich** [comment]
This change has been deployed.
