### ISSUE TITLE
Release Repository for ROS1 package

### ISSUE THREAD

**Issue by CAcarADI** [ros2-gbp/ros2-gbp-github-org#570]
My package is on ROS noetic (issue #569 ) and the ROS2 version is still on develop, is it okay to host my release repository for noetic here, then add the ROS2 version on the same repository as soon as the package is done?

**Comment by clalancette** [comment]
> My package is on ROS noetic (issue https://github.com/ros2-gbp/ros2-gbp-github-org/issues/569 ) and the ROS2 version is still on develop, is it okay to host my release repository for noetic here, then add the ROS2 version on the same repository as soon as the package is done?

Yes, that is an allowed workflow.

**Comment by CAcarADI** [comment]
Thanks, Ill close this issue now
