### ISSUE TITLE
Add `ai_prompt_msgs` release team

### ISSUE THREAD

**Issue by AndyZe** [ros2-gbp/ros2-gbp-github-org#571]
* Name of the new release team: `ai_prompt_msgs`
* Release repositories to add:

  * [ai_prompt_msgs](https://github.com/robosoft-ai/ai_prompt_msgs)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/30e3197c9cc9a39642e3a73c814ed0d5bb8af9fd/jazzy/distribution.yaml#L83)
  * [robosoft_openai](https://github.com/robosoft-ai/robosoft_openai)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/30e3197c9cc9a39642e3a73c814ed0d5bb8af9fd/jazzy/distribution.yaml#L5917)

* Team members
  * [@AndyZe](https://github.com/robosoft-ai/ai_prompt_msgs/blob/fa4d2354fd9770be891a6bcd32ff808fdeef95a9/package.xml#L7)

**Comment by nuclearsandwich** [comment]
This change has been deployed.
