### ISSUE TITLE
Add release team `fraunhofer_ipa_320`

### ISSUE THREAD

**Issue by ottojo** [ros2-gbp/ros2-gbp-github-org#573]
* Name of the new release team: `fraunhofer_ipa_320`
* Release repositories to add:
  * [ros_battery_monitoring](https://github.com/ipa320/ros_battery_monitoring.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/3f79811b26d897eb82f6594b88d2cc882e6a2db0/rolling/distribution.yaml#L6080)
    * [ ] There is an existing release repository which should be imported

* Team members
  * [@ottojo](https://github.com/ipa320/ros_battery_monitoring/blob/main/battery_state_rviz_overlay/package.xml#L7)

**Comment by nuclearsandwich** [comment]
This change has been deployed.
