### ISSUE TITLE
Add release team scenario_execution

### ISSUE THREAD

**Issue by fred-labs** [ros2-gbp/ros2-gbp-github-org#578]
* Name of the new release team: scenario_execution
* Release repositories to add:
  * [scenario_execution](https://github.com/intellabs/scenario_execution)
  * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/3e9af773826ee49ea09135314786d8a46085d9da/humble/distribution.yaml#L8807)
  * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

* Team members
  * [@fred-labs](https://github.com/IntelLabs/scenario_execution/blob/main/scenario_execution_ros/package.xml#L7)
  * [@fmirus](https://github.com/IntelLabs/scenario_execution/blob/main/scenario_execution_ros/package.xml#L8)

**Comment by fred-labs** [comment]
@nuclearsandwich friendly reminder.

**Comment by nuclearsandwich** [comment]
This change has been deployed.
