### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by HansRobo** [ros2-gbp/ros2-gbp-github-org#58]
* Name of the new release team: fortefibre
* Release repositories to add:
  * [fluent_rviz](https://github.com/ForteFibre/FluentRviz/tree/ros2)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

* Team members
  * [@shouth](https://github.com/ForteFibre/FluentRviz/blob/9512d3f5daa0df423a24547c1460dbb7eff086d7/package.xml#L7)
  * [@HansRobo](https://github.com/ForteFibre/FluentRviz/blob/9512d3f5daa0df423a24547c1460dbb7eff086d7/package.xml#L8)

**Comment by nuclearsandwich** [comment]
Deployed in #66.

**Comment by HansRobo** [comment]
@nuclearsandwich Thank you very much!!!
