### ISSUE TITLE
Add new release repositories for aerostack2 platforms

### ISSUE THREAD

**Issue by pariaspe** [ros2-gbp/ros2-gbp-github-org#583]
* Name of the release team: aerostack2

* Release repositories to add:
  
  * [as2_platform_crazyflie](https://github.com/aerostack2/as2_platform_crazyflie.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/38dcef7e304a90bb9044e16c7f0bbb4db04c52fd/humble/distribution.yaml#L584-L594)
    * [ ] There is an existing release repository which should be imported: NO
  * [as2_platform_dji_osdk]( https://github.com/aerostack2/as2_platform_dji_osdk.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/38dcef7e304a90bb9044e16c7f0bbb4db04c52fd/humble/distribution.yaml#L595-L605)
    * [ ] There is an existing release repository which should be imported: NO
  * [as2_platform_dji_psdk]( https://github.com/aerostack2/as2_platform_dji_psdk.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/38dcef7e304a90bb9044e16c7f0bbb4db04c52fd/humble/distribution.yaml#L606-L616)
    * [ ] There is an existing release repository which should be imported: NO
  * [as2_platform_mavlink]( https://github.com/aerostack2/as2_platform_mavlink.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/38dcef7e304a90bb9044e16c7f0bbb4db04c52fd/humble/distribution.yaml#L617-L627)
    * [ ] There is an existing release repository which should be imported: NO
  * [as2_platform_pixhawk]( https://github.com/aerostack2/as2_platform_pixhawk.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/38dcef7e304a90bb9044e16c7f0bbb4db04c52fd/humble/distribution.yaml#L628-L638)
    * [ ] There is an existing release repository which should be imported: NO
  * [as2_platform_tello]( https://github.com/aerostack2/as2_platform_tello.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/38dcef7e304a90bb9044e16c7f0bbb4db04c52fd/humble/distribution.yaml#L639-649)
    * [ ] There is an existing release repository which should be imported: NO

**Comment by nuclearsandwich** [comment]
This change has been deployed.
