### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by chama1176** [ros2-gbp/ros2-gbp-github-org#584]
# Updates to rt_net_team membership.

## New team members

* [@chama1176](https://github.com/rt-net/rt_manipulators_cpp/blob/cf8726bc1152f59f599db139f5cfa5b73bdc6317/rt_manipulators_lib/package.xml#L11)

## Retiring team members

* [@shu-rt](https://github.com/rt-net/raspimouse_description/blob/04a3d1f1abce0d7fdd71c0d9a4adfdeee955ff7b/package.xml#L10)
* [@Tiryoh](https://github.com/rt-net/raspimouse_description/blob/04a3d1f1abce0d7fdd71c0d9a4adfdeee955ff7b/package.xml#L8)

**Comment by nuclearsandwich** [comment]
@chama1176 there isn't a `shu-rt` in the team currently. Did you mean [`shu-13`](https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/rt_net.tf#L7)?

**Comment by chama1176** [comment]
@nuclearsandwich 
That's right.
I made a mistake in my description.

**Comment by nuclearsandwich** [comment]
Although this change has merged it has not yet been deployed. Please see https://github.com/ros2-gbp/ros2-gbp-github-org/issues/618 for updates.

**Comment by nuclearsandwich** [comment]
This change has been deployed!
