### ISSUE TITLE
Add new release repository: ffmpeg_encoder_decoder

### ISSUE THREAD

**Issue by berndpfrommer** [ros2-gbp/ros2-gbp-github-org#596]
* Name of the release team: ros-misc-utilities

* Release repositories to add:
  
  * [ffmpeg_encoder_decoder](https://github.com/ros-misc-utilities/ffmpeg_encoder_decoder)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/278b8b6a3535d64995ec5200c3e9fa8d564319d2/jazzy/distribution.yaml#L1688)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

**Comment by nuclearsandwich** [comment]
Although this change has merged it has not yet been deployed. Please see https://github.com/ros2-gbp/ros2-gbp-github-org/issues/618 for updates.

**Comment by nuclearsandwich** [comment]
Although this change has merged it has not yet been deployed. Please see https://github.com/ros2-gbp/ros2-gbp-github-org/issues/618 for updates.

**Comment by nuclearsandwich** [comment]
This change has been deployed!
