### ISSUE TITLE
Add release team: sick_safetyscanners

### ISSUE THREAD

**Issue by lenpuc** [ros2-gbp/ros2-gbp-github-org#597]
* Name of the new release team: sick_safetyscanners
* Release repositories to add:
  
  * [sick_safetyscanners_base](https://github.com/SICKAG/sick_safetyscanners_base/tree/ros2)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/master/iron/distribution.yaml#L7316)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>
  * [sick_safetyscanners2_interfaces](https://github.com/SICKAG/sick_safetyscanners2_interfaces)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/master/iron/distribution.yaml#L7301)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>
   * [sick_safetyscanners2](https://github.com/SICKAG/sick_safetyscanners2)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/master/iron/distribution.yaml#L7276)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

* Team members
  * [@puck-fzi](https://github.com/SICKAG/sick_safetyscanners2/blob/master/package.xml#L7)

I am unsure about the migration of the previous release repos. Is this something that should be done even for older distros? Should humble and iron be moved to the new repository, or is this currently limited for jazzy and rolling? Asking concerning: https://github.com/ros/rosdistro/pull/42513, for humble and iron the merges were accepted. Since this is the first release for both jazzy and rolling. I would be fine with just creating a new release repo for these tracks and continuing forward from them but I would adhere to the best practices there.

**Comment by nuclearsandwich** [comment]
> Is this something that should be done even for older distros?

For convenience we recommend all active ROS 2 distributions use the same release repository, so that would include releases for Humble and Iron.

Mirroring the existing artifacts to the ros2-gbp repositories is very straightforward (even easier than only moving some artifacts) so my recommendation is to update all distros to use the ros2-gbp repositories and archive the previous repositories in order to prevent accidentally pushing to them once the switch is made.

**Comment by nuclearsandwich** [comment]
Although this change has merged it has not yet been deployed. Please see https://github.com/ros2-gbp/ros2-gbp-github-org/issues/618 for updates.

**Comment by nuclearsandwich** [comment]
This change has been deployed. Additionally, I have mirrored the previous release repositories to their ros2-gbp counterparts. If you archive the previous release repositories you can either manually update the release repository urls in ros/rosdistro before your next bloom release or use the `--override-release-repository-url` option.
