### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by VinDp** [ros2-gbp/ros2-gbp-github-org#604]
# Updates to universal_robots membership.

## New team members

* [@VinDp](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/76402a543dadcaf55d422905af53be249f0b9724/ur_robot_driver/package.xml#L9)

**Comment by nuclearsandwich** [comment]
Although this change has merged it has not yet been deployed. Please see https://github.com/ros2-gbp/ros2-gbp-github-org/issues/618 for updates.

**Comment by nuclearsandwich** [comment]
This change has been deployed!
