### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by arthurgomes4** [ros2-gbp/ros2-gbp-github-org#605]
# Updates to black_coffee_robotics membership.

## New team members
* [arthurgomes4](https://github.com/blackcoffeerobotics/vector_pursuit_controller/blob/788597c98abc1d37d7575314ca8e4dda688329b6/package.xml#L9)
* [exMachina316](https://github.com/blackcoffeerobotics/vector_pursuit_controller/blob/788597c98abc1d37d7575314ca8e4dda688329b6/package.xml#L7)

**Comment by nuclearsandwich** [comment]
Although this change has merged it has not yet been deployed. Please see https://github.com/ros2-gbp/ros2-gbp-github-org/issues/618 for updates.

**Comment by nuclearsandwich** [comment]
This change has been deployed!
