### ISSUE TITLE
Add new release repository: foxglove_compressed_video_transport

### ISSUE THREAD

**Issue by berndpfrommer** [ros2-gbp/ros2-gbp-github-org#619]
* Name of the release team: ros-misc-utilities

* Release repositories to add:
 
  * [foxglove_compressed_video_transport](https://github.com/ros-misc-utilities/foxglove_compressed_video_transport/)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/84ed5f4b5b37e945843e74a479709d6f77704c89/humble/distribution.yaml#L2559)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

**Comment by nuclearsandwich** [comment]
This change has been deployed.
