### ISSUE TITLE
Add new release repositories

### ISSUE THREAD

**Issue by VinDp** [ros2-gbp/ros2-gbp-github-org#621]
* Name of the release team: universal_robots_team

* Release repositories to add:
  
  * [Universal_Robots_ROS2_GZ_Simulation-release](https://github.com/UniversalRobots/Universal_Robots_ROS2_GZ_Simulation)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/3fd784b8d919625644eabd47d50958a87ab8733c/jazzy/distribution.yaml#L8659)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

**Comment by nuclearsandwich** [comment]
This change has been deployed.
