### ISSUE TITLE
Add simple_grasping release team

### ISSUE THREAD

**Issue by mikeferguson** [ros2-gbp/ros2-gbp-github-org#627]
* Name of the new release team: simple_grasping
* Release repositories to add:

  * [simple_grasping](https://github.com/mikeferguson/simple_grasping)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/commit/89eb119b911ffc05e03cb3742cbaeaf38a52c302)
    * [x] No existing release repository for ROS 2
  * [grasping_msgs](https://github.com/mikeferguson/grasping_msgs)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/commit/bc8aa818cae2fd5cb0881612e9ad02964c39e528)
    * [x] There is an existing release repository which should be imported: https://github.com/mikeferguson/grasping_msgs-ros2-gbp

* Team members
  * @mikeferguson You'll notice both source repos are under my account
 
grasping_msgs is already released into humble/iron/jazzy - wanting to release into rolling, hence the moving of the GBP. simple_grasping was available in ROS 1, now getting it released into ROS 2 (especially since it is featured in an upcoming ROSCON talk later this month). I would normally just create a PR with the changes - but not sure how we do the import of an existing GBP.

**Comment by nuclearsandwich** [comment]
https://github.com/mikeferguson/grasping_msgs-ros2-gbp has been mirrored into https://github.com/ros2-gbp/grasping_msgs-release

**Comment by nuclearsandwich** [comment]
This change has been deployed.
