### ISSUE TITLE
Add wasp_research_group release team

### ISSUE THREAD

**Issue by ajtudela** [ros2-gbp/ros2-gbp-github-org#630]
* Name of the new release team: wasp_research_group
* Release repositories to add:
  
  * [slg_msgs](https://github.com/ajtudela/slg_msgs)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L9441)
    * [ ] No existing release repository for ROS 2
  * [laser_segmentation](https://github.com/ajtudela/laser_segmentation)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L3793)
    * [ ] No existing release repository for ROS 2

* Team members
  * [@ajtudela](https://github.com/ajtudela/slg_msgs/blob/main/package.xml#L7)
  * [@MFernandezCarmona](https://github.com/ajtudela/laser_segmentation/blob/main/package.xml#L8)

**Comment by nuclearsandwich** [comment]
This change has been deployed.
