### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by luca-della-vedova** [ros2-gbp/ros2-gbp-github-org#634]
# Updates to rmf membership.

## New team members

* [@luca-della-vedova](https://github.com/open-rmf/rmf_simulation/blob/9e0e5b70d67573ae9519c59d1e27d8b380b57f0e/rmf_robot_sim_common/package.xml#L9) and ther packages such as  [1](https://github.com/open-rmf/rmf_simulation/blob/9e0e5b70d67573ae9519c59d1e27d8b380b57f0e/rmf_building_sim_gz_plugins/package.xml#L11), [2](https://github.com/open-rmf/rmf_simulation/blob/9e0e5b70d67573ae9519c59d1e27d8b380b57f0e/rmf_robot_sim_gz_plugins/package.xml#L11), [3](https://github.com/open-rmf/rmf_demos/blob/b1636b0de7d2bf951c613e3d5b9fc3bf46fc9a2b/rmf_demos_gz/package.xml#L8)

**Comment by nuclearsandwich** [comment]
This change has been deployed.
