### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by KuraZuzu** [ros2-gbp/ros2-gbp-github-org#637]
# Updates to [rt_net_team](https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/rt_net.tf) membership.

## New team members

* [@KuraZuzu](https://github.com/rt-net/raspimouse2/blob/master/raspimouse/package.xml#L15)

## Retiring team members

* [@ShotaAk](https://github.com/rt-net/raspimouse2/blob/master/raspimouse/package.xml#L10)

**Comment by nuclearsandwich** [comment]
This change has been deployed.

**Comment by KuraZuzu** [comment]
Thank you very much !!
