### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by Smith-JackSmith** [ros2-gbp/ros2-gbp-github-org#645]
# Updates to franka_robotics membership.

## New team members

* [@Smith-JackSmith]
* [@ssilenzi]

## Current Members include
[@AndreasKuhner]
[@gomezgu]
[@BarisYazici]
[@winkma]

**Comment by nuclearsandwich** [comment]
@Smith-JackSmith can you please update the issue body to include links to your maintainer entries in franka_robotics repositories. Or else have two current members of the team 👍🏼 this request.

**Comment by Smith-JackSmith** [comment]
It appears I need more information - surprise - because, as far as I can see, there isn't any team named "franka_robotics_team" .

**Comment by Smith-JackSmith** [comment]
Are you suggesting that I either:

1.) Edit this request, adding , into the body of the request, the GitHub user ID of the people responsible for the github repository (or group of repositories) that I wish to have access to. 

Or, 

2.) ask two members of the team named "franka_robotics_team" to access this github request (on GitHub) and approve it ,  somehow. 

Both those suggestions, while sensible, imply a degree of knowledge and understanding that is not matched in reality.  I'll look into this as soon as possible.

**Comment by nuclearsandwich** [comment]
There's an existing release team here: https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/franka_robotics.tf

What would be the difference between the newly proposed team and this existing one?

**Comment by Smith-JackSmith** [comment]
I was told the group name "franka_robotics_release" , but, maybe there was some confusion about what it is really named.

All of the names listed in the team,  "franka_robotics" -   [franka_robotics](https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/franka_robotics.tf) -  appear to be the people on my development team.  So, I'm pretty sure that's what is intended

**Comment by Smit-tay** [comment]
@nuclearsandwich 

Please explain the phrase :  maintainer entries in franka_robotics

Is there an GitHub attribute of a GitHub team member that is a GitHub team "maintainer", or is this at the GitHub repository level ?

Or, are you referring to this:

`<maintainer email="support@franka.de">Franka Robotics GmbH</maintainer>`

Which I guess is the "maintainer entry" for all of Franka Robotics packages as required in package.xml

**Comment by Smith-JackSmith** [comment]
This was me - my Alter Ego

> @nuclearsandwich
> 
> Please explain the phrase : maintainer entries in franka_robotics
> 
> Is there an GitHub attribute of a GitHub team member that is a GitHub team "maintainer", or is this at the GitHub repository level ?
> 
> Or, are you referring to this:
> 
> `<maintainer email="support@franka.de">Franka Robotics GmbH</maintainer>`
> 
> Which I guess is the "maintainer entry" for all of Franka Robotics packages as required in package.xml

**Comment by AndreasKuhner** [comment]
Hi @nuclearsandwich ,
yes, this is the one: https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/franka_robotics.tf - there we have our 2 new members [@Smith-JackSmith] and [@ssilenzi].

@BarisYazici can you also please thumbs up the initial post?

Cheers,
Andreas

**Comment by Smith-JackSmith** [comment]
@nuclearsandwich 

Do we have an expected completion date for this request?

**Comment by tfoote** [comment]
@Smith-JackSmith Please make sure that there is a comment back when there's an update to be reviewed by the maintainers. I see that @BarisYazici thumbs upped the post, but that doesn't generate a notification for maintainers to know that this is completed. So a comment back can help. We do periodic updates on this repository, and can usually action things within a few days. But with holidays sometimes it takes longer. 

If you'd like to make it easier and faster you could open a PR against https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/franka_robotics.tf and reference this for the approval. PRs make it easier for the maintainers to review and merge quickly.

**Comment by Smith-JackSmith** [comment]
@tfoote 
Thank you for the reply.
Can you tell me what the status of this is issue is, please.

I followed the instructions for this, and submitted the template found here: [Template](https://github.com/ros2-gbp/ros2-gbp-github-org/issues/new/choose).

I have responded to all questions, immediately, I am unclear about  the current status of this issue.

**Comment by tfoote** [comment]
It looks like you've gotten approvals from 2 existing maintainers as requested above. So now it requires a maintainer to come by and turn that into a PR validate it and then merge it on their next pass. If you make the PR to enact that it will make it lower effort and thus a maintainer taking a pass will need less time. I suspect that the next pass on this will be in a couple of days. The main thing that this was waiting on was approval by the existing maintainers which was just verified by me 11 minutes ago.

**Comment by Smith-JackSmith** [comment]
Which maintainer are you referring to? 

The repository holding the team configuration file is owned/permissioned  by some group of ros2 people, not any of our Franka developers listed in the team configuration file.

The instructions don't say anything about creating a pull request on that file.  If that is really the process, why isn't it documented?

**Comment by tfoote** [comment]
It's not waiting on the maintainers of this repository to do their next batch update. Because this is granting access there's a strong manual review process and it requires putting aside focus time and as you've seen above requires all the verifications for us to move forward. We don't want to rush security. 

The PR is not required, but for those with technical knowledge and capabilities it can help accelerate things which you seem interested in. There's some documentation in the CONTRIBUTING.md https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/CONTRIBUTING.md Because PRs are much more concrete they are less ambiguous and consequently make the reviews easier, as well as avoid risks of typos along the way etc.

**Comment by Smith-JackSmith** [comment]
"It's not waiting..." 

I'm guessing that is a typo, and should read: "It's now waiting". 

Otherwise, if it's not waiting on the maintainers, what is it waiting for next?

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Comment by AndreasKuhner** [comment]
Thanks @tfoote and @nuclearsandwich :partying_face:
