### ISSUE TITLE
Add release repository adi_3dtof_image_stitching

### ISSUE THREAD

**Issue by raebelchristo-adi** [ros2-gbp/ros2-gbp-github-org#646]
* analogdevices_robotics_sys_sw: 

* Release repositories to add:
  
  * [adi_3dtof_image_stitching](https://github.com/analogdevicesinc/adi_3dtof_image_stitching/tree/humble-devel)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L85)
    * [ ] Creating a release repository

**Comment by nuclearsandwich** [comment]
Resolved by #647.

**Comment by nuclearsandwich** [comment]
This change has been deployed.
