### ISSUE TITLE
Add release team: cognipilot

### ISSUE THREAD

**Issue by bperseghetti** [ros2-gbp/ros2-gbp-github-org#648]
* Name of the new release team: cognipilot
* Release repositories to add:
  * [ros2_psutil_msgs](https://github.com/CogniPilot/ros2_psutil_msgs)
    * [ros/rosdistro source entry](LINK TO SOURCE FIELD IN ROS/ROSDISTRO)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>
  * [ros2_psutil](https://github.com/CogniPilot/ros2_psutil)
    * [ros/rosdistro source entry](LINK TO SOURCE FIELD IN ROS/ROSDISTRO)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>
  * [synapse_msgs](https://github.com/CogniPilot/synapse_msgs)
    * [ros/rosdistro source entry](LINK TO SOURCE FIELD IN ROS/ROSDISTRO)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

* Team members
  * [@bperseghetti](https://github.com/CogniPilot/ros2_psutil_msgs/blob/8d53087a6fa970047cd62f757808f6b66a5a174f/package.xml#L7)
  * [@jgoppert](https://github.com/CogniPilot/synapse_msgs/blob/ceb3330b622dad830dd76c38f35bd7548dcf1a7c/package.xml#L7)

**Comment by nuclearsandwich** [comment]
This change has been deployed.
