### ISSUE TITLE
Add release team pradyum_group

### ISSUE THREAD

**Issue by pradyum** [ros2-gbp/ros2-gbp-github-org#649]
* Name of the new release team: pradyum_group
* Release repositories to add:
  
  * [dual_laser_merger](https://github.com/pradyum/dual_laser_merger)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/93cff5f8f227cb7dd2f61668c2130045e97eac5e/rolling/distribution.yaml#L1198)
    * [ ] No existing release repository for ROS 2

* Team members
  * [@pradyum](https://github.com/pradyum/dual_laser_merger/blob/ff1edbf1e17136e4f92d3b0523f1c701cf757cff/package.xml#L7)

**Comment by nuclearsandwich** [comment]
This change has been deployed.
