### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by Myzhar** [ros2-gbp/ros2-gbp-github-org#652]
* Name of the new release team: Stereolabs
* Release repositories to add:
  
  * [zed-ros2-interfaces](https://github.com/stereolabs/zed-ros2-interfaces.git)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L11438-L11443)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

* Team members
  * [@Myzhar](https://github.com/stereolabs/zed-ros2-interfaces/blob/main/package.xml#L8)
  * [@adujardin](https://github.com/stereolabs/zed-ros2-interfaces/blob/main/package.xml#L9)
  * [@obraun-sl](https://github.com/stereolabs/zed-ros2-interfaces/blob/main/package.xml#L10)
  * [@P-yver](https://github.com/stereolabs/zed-ros2-interfaces/blob/main/package.xml#L11)

**Comment by Myzhar** [comment]
@nuclearsandwich I cannot find `https://github.com/ros2-gbp/zed-ros2-interfaces.git` while using `bloom-release`.
Did I miss a step somewhere?

**Comment by nuclearsandwich** [comment]
> @nuclearsandwich I cannot find `https://github.com/ros2-gbp/zed-ros2-interfaces.git` while using `bloom-release`.
> Did I miss a step somewhere?

The merged changes are still being deployed. I'll post a comment when the terraform deployment is completed.

**Comment by nuclearsandwich** [comment]
@Myzhar the changes have now been deployed.
