### ISSUE TITLE
Add release team uw_graphics

### ISSUE THREAD

**Issue by cpsiff** [ros2-gbp/ros2-gbp-github-org#660]
* Name of the new release team: uw_graphics
* Release repositories to add:
  
  * [mini_tof](https://github.com/uwgraphics/mini_tof)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/pull/43540)
  * [mini_tof_interfaces](https://github.com/uwgraphics/mini_tof_interfaces)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/pull/43540)

* Team members
  * @cpsiff [[mini_tof author tag](https://github.com/uwgraphics/mini_tof/blob/819797f17874831a2f34930953fabe48798ac946/package.xml#L8)][[mini_tof_interfaces author tag](https://github.com/uwgraphics/mini_tof_interfaces/]blob/8711d7c3633daecf435c8a40f4b9e8f682707590/package.xml#L8)]

**Comment by nuclearsandwich** [comment]
This change has been deployed!
