### ISSUE TITLE
Add release team `sony_rdc`

### ISSUE THREAD

**Issue by fujitatomoya** [ros2-gbp/ros2-gbp-github-org#664]
* Name of the new release team: sony_rdc
* Release repositories to add:
  * [ros2_service_load_balancing](https://github.com/Barry-Xu-2018/ros2_service_load_balancing)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/00de49f5efa7b1060598d6e079193f2eed1d11ca/rolling/distribution.yaml#L7372-L7377)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

* Team members
  * [@Barry-Xu-2018](https://github.com/Barry-Xu-2018/ros2_service_load_balancing/blob/main/package.xml#L7)
  * [@fujitatomoya](https://github.com/Barry-Xu-2018/ros2_service_load_balancing/blob/main/package.xml#L8)

**Comment by fujitatomoya** [comment]
Is there anything we need to do on our side?

**Comment by nuclearsandwich** [comment]
This change has been deployed!

**Comment by fujitatomoya** [comment]
@nuclearsandwich thanks, appreciate it!
