### ISSUE TITLE
Add release team `4am_robotics`

### ISSUE THREAD

**Issue by Deleh** [ros2-gbp/ros2-gbp-github-org#665]
* Name of the new release team: 4am_robotics
* Release repositories to add:
  
  * [cob_common](https://github.com/4am-robotics/cob_common)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/46160a58090791131932deee4057d40b39564885/humble/distribution.yaml#L1395)
    * [x] There is an existing release repository which should be imported: https://github.com/4am-robotics/cob_common-release

* Team members
  * [@benmaidel](https://github.com/4am-robotics/cob_common/blob/f3854c63975f905c38aace72371197febe8bfc6a/cob_common/package.xml#L12)
  * [@Deleh](https://github.com/4am-robotics/cob_common/blob/f3854c63975f905c38aace72371197febe8bfc6a/cob_common/package.xml#L13)

**Comment by nuclearsandwich** [comment]
This change has been deployed!
