### ISSUE TITLE
Add repositories to team "franka_release"

### ISSUE THREAD

**Issue by Smith-JackSmith** [ros2-gbp/ros2-gbp-github-org#667]
* [libfranka](https://github.com/frankaemika/libfranka.git)
    * [ros/humble source entry - libfranka](https://github.com/ros/rosdistro/blob/0d66d7f62975229ed0b1031137f8324ee568cc3e/humble/distribution.yaml#L4217)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>
* [franka_ros2](https://github.com/frankaemika/franka_ros2.git)
    * [ros/humble source entry - franka_ros2](https://github.com/ros/rosdistro/blob/0d66d7f62975229ed0b1031137f8324ee568cc3e/humble/distribution.yaml#L2714)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>

**Comment by Smith-JackSmith** [comment]
@nuclearsandwich - Can you please revisit this issue, I have provided a PR **[here](https://github.com/ros2-gbp/ros2-gbp-github-org/pull/683)**

**Comment by nuclearsandwich** [comment]
This change has been deployed.

**Comment by Smith-JackSmith** [comment]
Thank you, @nuclearsandwich
