### ISSUE TITLE
Add release team automatika_robotics

### ISSUE THREAD

**Issue by mkabtoul** [ros2-gbp/ros2-gbp-github-org#669]
* Name of the new release team: automatika_robotics
* Release repositories to add:

  * [automatika_ros_sugar](https://github.com/automatika-robotics/ros-sugar)
    * [ros/rosdistro source entry](https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L734)
    * [x] There is an existing release repository which should be imported: <[RELEASE REPOSITORY URL](https://github.com/automatika-robotics/ros-sugar-release.git)>

* Team members
  * [@mkabtoul](https://github.com/automatika-robotics/ros-sugar/blob/main/package.xml#L7)
  * [@aleph-ra](https://github.com/automatika-robotics/ros-sugar/blob/main/package.xml#L7)

**Comment by nuclearsandwich** [comment]
This change has been deployed!
