### ISSUE TITLE
Add release team "jafarabdi"

### ISSUE THREAD

**Issue by JafarAbdi** [ros2-gbp/ros2-gbp-github-org#673]
* Name of the new release team: jafarabdi
* Release repositories to add:
  
  * https://github.com/JafarAbdi/feetech_ros2_driver
    * https://github.com/ros/rosdistro/pull/43490
    * [x] There is an existing release repository which should be imported: https://github.com/JafarAbdi/feetech_ros2_driver-release
  * https://github.com/JafarAbdi/jacro
    * https://github.com/ros/rosdistro/pull/43494
    * [x] There is an existing release repository which should be imported: https://github.com/JafarAbdi/jacro-release
  * ...

* Team members
  * @JafarAbdi

**Comment by nuclearsandwich** [comment]
This change has been deployed!
