### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by boitumeloruf** [ros2-gbp/ros2-gbp-github-org#675]
# Updates to fraunhofer_iosb_ars membership.

## New team members
* [@rapzag](https://github.com/rapzag)
* [@migranram](https://github.com/migranram)

## Retiring team members

* [@boitumeloruf](https://github.com/FraunhoferIOSB/camera_aravis2/commit/45806a12edf457b314ad1da73bceb00eb19ebab8)

**Comment by nuclearsandwich** [comment]
This change has been deployed!
