### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by ShotaAk** [ros2-gbp/ros2-gbp-github-org#82]
* Name of the new release team: rt_net
* Release repositories to add:
  * [raspimouse_description](https://github.com/rt-net/raspimouse_description)
    * [x] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>
  * [raspimouse2](https://github.com/rt-net/raspimouse2)
    * [x] There is an existing release repository which should be imported: https://github.com/rt-net/raspimouse2-release<RELEASE REPOSITORY URL>

* Team members
  * [@ShotaAk](https://github.com/rt-net/raspimouse_description/blob/04a3d1f1abce0d7fdd71c0d9a4adfdeee955ff7b/package.xml#L9)
  * [@shu-rt](https://github.com/rt-net/raspimouse_description/blob/04a3d1f1abce0d7fdd71c0d9a4adfdeee955ff7b/package.xml#L10)
  * [@Tiryoh](https://github.com/rt-net/raspimouse_description/blob/04a3d1f1abce0d7fdd71c0d9a4adfdeee955ff7b/package.xml#L8)

**Comment by nuclearsandwich** [comment]
#82 has been merged and deployed.

**Comment by Tiryoh** [comment]
@nuclearsandwich Thanks!
