### ISSUE TITLE
Add new release repositories for rt_net

### ISSUE THREAD

**Issue by ShotaAk** [ros2-gbp/ros2-gbp-github-org#87]
* Name of the release team: rt_net

* Release repositories to add:
  * [raspimouse_ros2_examples](https://github.com/rt-net/raspimouse_ros2_examples)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>
  * [raspimouse_slam_navigation_ros2](https://github.com/rt-net/raspimouse_slam_navigation_ros2)
    * [ ] There is an existing release repository which should be imported: <RELEASE REPOSITORY URL>
  * [rt_manipulators_cpp](https://github.com/rt-net/rt_manipulators_cpp)
    * [ ] There is an existing release repository which should be imported: https://github.com/rt-net-gbp/rt_manipulators_cpp-release
  * [rt_usb_9axisimu_driver](https://github.com/rt-net/rt_usb_9axisimu_driver)
    * [ ] There is an existing release repository which should be imported: https://github.com/rt-net-gbp/rt_usb_9axisimu_driver-release
  * [crane_plus](https://github.com/rt-net/crane_plus)
    * [ ] There is an existing release repository which should be imported: https://github.com/rt-net-gbp/crane_plus-release

**Comment by ijnek** [comment]
@cottsay Since @nuclearsandwich is out of office, would you or someone else from the ros2 team be able to respond to this request, and the other pending requests #88, #89 and #92 please?

**Comment by cottsay** [comment]
Deployed in #94
