### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by malban** [ros2-gbp/ros2-gbp-github-org#88]
* Name of the new release team: hatchbed

* Release repositories to add:
  * [log_view](https://github.com/hatchbed/log_view)
    * [x] There is an existing release repository which should be imported: https://github.com/hatchbed/log_view-release
  * [asyncapi_gencpp](https://github.com/hatchbed/asyncapi_gencpp) 
  * [rpad](https://github.com/hatchbed/rpad)
  * [rpad_ros](https://github.com/hatchbed/rpad_ros)
  * [param_util](https://github.com/hatchbed/param_util)

Team Members:
  * @malban
  * @pjreed

**Comment by cottsay** [comment]
The repository "param_util" is a pretty generic name. Could you please open a PR to add `source` stanzas for these packages to one of the distributions in [ros/rosdistro](https://github.com/ros/rosdistro)? That's often where we discuss package/repository naming.

If it makes it into an official distro, then I'm happy to create a release repository for it.

**Comment by malban** [comment]
Sure thing.  Yeah, naming things is hard.  I can come up with something else if necessary.

**Comment by nuclearsandwich** [comment]
I'm going to close this for now pending the discussion in https://github.com/ros/rosdistro/pull/34108 but we can reopen it once that has settled.
