### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by joshnewans** [ros2-gbp/ros2-gbp-github-org#89]
*The instructions said that an individual's name is ok, but none of the others currently in the repo seem to be. My package/s will be too small to warrant per-package teams either. I've gone with my name anyway as it matches my Github username, but also happy to go with my "brand" articulated_robotics if that is preferred, in the case of future maintainers joining my projects.*
* Name of the new release team: josh_newans 
* Release repositories to add:
  * [twist_stamper](https://github.com/joshnewans/twist_stamper)
    * [x] There is an existing release repository which should be imported: https://github.com/joshnewans/twist_stamper-release

* Team members
  * @joshnewans [Maintainer tag](https://github.com/joshnewans/twist_stamper/blob/32e0eed68c76d9d3fa64b54e8313aa9a6d6bd99d/package.xml#L7)

**Comment by ijnek** [comment]
Although there aren't many, here are some:
* https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/wep21.tf
* https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/ijnek.tf

**Comment by joshnewans** [comment]
Hey @cottsay  I thought I'd tag as I saw you were updating some of the other requests yesterday.
Would it be possible to get mine pushed through so I can move forward with releasing my package to newer distros?
Thanks :)

**Comment by cottsay** [comment]
Deployed in #100.
