### ISSUE TITLE
Add new release repositories

### ISSUE THREAD

**Issue by ijnek** [ros2-gbp/ros2-gbp-github-org#92]
* Name of the release team: sports

* Release repositories to add:
  * [vision_msgs_layers](https://github.com/ros-sports/vision_msgs_layers.git)
    * [ ] There is no existing release repository
  * [soccer_vision_2d_layers](https://github.com/ros-sports/soccer_vision_2d_layers.git)
    * [ ] There is no existing release repository

**Comment by cottsay** [comment]
Deployed in #95

**Comment by ijnek** [comment]
Thanks!
