### ISSUE TITLE
Update release team membership

### ISSUE THREAD

**Issue by febu1300** [ros2-gbp/ros2-gbp-github-org#93]
# Updates to  membership.

## New team members

* [@febu1300](LINK TO https://github.com/febu1300/ros2can/blob/master/package.xml Buruk T. Fetene/febu)

## Retiring team members

* [@GITHUB_USERNAME](LINK TO SOURCE COMMIT OR PULL REQUEST UPDATING MAINTAINER INFORMATION)

**Comment by nuclearsandwich** [comment]
@febu1300 the linked repository looks like it includes both release info and bloom data when these are usually separate repositories.

I would suggest removing the bloom data from this source repository before setting up a new release repository in the ros2-gbp organization.

**Comment by nuclearsandwich** [comment]
@febu1300 a friendly ping. If you have any questions about the recommended cleanup please let me know.

**Comment by febu1300** [comment]
Thank you for the ping.
I'm not sure I get what you mean, I'm new here, just trying out what works,
not trying to cause any trouble :)
 I deleted all the other branches except for the master, " removing the
bloom data "? Shall I delete the track.yaml file?
regards,
febu1300

**Comment by nuclearsandwich** [comment]
Yes I would suggest deleting that as well. Those files and branches will be created in the release repository once it is created. They do not need to be in the source repository and will only create confusion if present.

**Comment by nuclearsandwich** [comment]
@febu1300 I am going to close this issue for now. Please re-open it when you have the chance to update the source repository. Let me know if I can answer any other questions.
