### ISSUE TITLE
Add release team

### ISSUE THREAD

**Issue by SkyloveQiu** [ros2-gbp/ros2-gbp-github-org#96]
* Sky^2
* Release repositories to add:
  * [Robotino_ROS2](https://github.com/SkyloveQiu/ROS2_Robotino)
       * [x] There is an existing release repository which should be imported: <https://github.com/SkyloveQiu/ROS2_Robotino>
  * Team members
  * [@SkyloveQiu](https://github.com/SkyloveQiu/ROS2_Robotino/blob/master/src/robotino_ros2/package.xml)

**Comment by cottsay** [comment]
Hi, @SkyloveQiu -

Please choose a release team name which contains only alphanumeric characters.

**Comment by SkyloveQiu** [comment]
@cottsay then please use Skylove
