### ISSUE TITLE
Add new release repositories

### ISSUE THREAD

**Issue by arne48** [ros2-gbp/ros2-gbp-github-org#97]
* Name of the release team: rqt

* Release repositories to add:
  * [ros-visualization/rqt_tf_tree](https://github.com/ros-visualization/rqt_tf_tree)
    * [ ] There is an existing release repository which should be imported: [ros2-gbp/rqt_tf_tree-release](https://github.com/ros2-gbp/rqt_tf_tree-release)

Currently it turns out to be complicated to release a new version of rqt_tf_tree for humble.
I was told  ([https://github.com/ros-visualization/rqt_tf_tree/issues/42](https://github.com/ros-visualization/rqt_tf_tree/issues/42)) that the correct way to talk about permission topics are issues an PRs in this repository as permissions are automatically generated for the ROS2 release repositories.
The problem with missing releases was also already brought up on [discourse](https://discourse.ros.org/t/preparing-for-humble-sync-2022-08-17/26882).
I actually don't know why this specific rqt repository is not part of the list of repositories available to the rqt release maintainers but maybe it is possible to add this now so we can release rqt_tf_tree for new distributions.

**Comment by nuclearsandwich** [comment]
> I actually don't know why this specific rqt repository is not part of the list of repositories available to the rqt release maintainers but maybe it is possible to add this now so we can release rqt_tf_tree for new distributions.

When this repository was originally configured it permissions were set based on prior activity. Since the previous releases were made by ROS 2 core team members, that was the first place I added the repository. I've opened a PR which will give release permissions to the rqt team as well.

**Comment by arne48** [comment]
Thank you very much for the explanation @nuclearsandwich. I guessed it must have been something of that nature.
And also thank very much for already opening a PR. :)
